import { FontItem, LogoPreset } from './types';
import { getExtraFonts } from './extraFonts';

const BASE_FONTS: FontItem[] = [
  // --- SCRIPTS / CALLIGRAPHY (30+ fonts from beautiful handwriting) ---
  {
    id: 'great-vibes',
    name: 'Great Vibes',
    arabicCategory: 'خط مكتوب / خط يدويّ أثير',
    category: 'script',
    family: '"Great Vibes", cursive',
    source: 'Google Fonts',
    author: 'TypeSETit',
    description: 'A beautifully flowing, elegant script with smooth climbs and descents.',
    arabicDescription: 'خط يدوي انسيابي وأنيق للغاية مع صعود وهبوط سلس للحروف، ممتاز للتصاميم الفاخرة.',
    recommendedUse: 'Luxury labels, wedding invites, elegant logos.',
    arabicRecommendedUse: 'الملصقات الفاخرة، دعوات الزفاف، والشعارات الراقية.'
  },
  {
    id: 'windsong',
    name: 'WindSong',
    arabicCategory: 'خط يد سريع وحاد',
    category: 'script',
    family: '"WindSong", cursive',
    source: 'Google Fonts',
    author: 'Bright Crown',
    description: 'An expressive, fast-paced calligraphy style with a hand-written organic look.',
    arabicDescription: 'أسلوب خط يدوي سريع ومعبّر ومميز يعطي طابعاً طبيعياً وعفوياً نابضاً بالحيوية.',
    recommendedUse: 'Organic branding, cosmetic logos, signature branding.',
    arabicRecommendedUse: 'العلامات التجارية العضوية، مستحضرات التجميل، وشعارات التواقيع.'
  },
  {
    id: 'sacramento',
    name: 'Sacramento',
    arabicCategory: 'خط كلاسيكي نحيف ومتصل',
    category: 'script',
    family: '"Sacramento", cursive',
    source: 'Google Fonts',
    author: 'Astigmatic',
    description: 'A monoline cursive inspired by mid-century hand-lettering brochure designs.',
    arabicDescription: 'خط يدوي متصل ذو سماكة موحدة مستوحى من تصاميم الكتيبات الدعائية في منتصف القرن الماضي.',
    recommendedUse: 'Retro signage, delicate branding, poetry layout.',
    arabicRecommendedUse: 'اللوحات القديمة، الهويات الدقيقة، وتنسيق القصائد الأدبية.'
  },
  {
    id: 'pacifico',
    name: 'Pacifico',
    arabicCategory: 'خط فونتج سميك ومبهج',
    category: 'script',
    family: '"Pacifico", cursive',
    source: 'Google Fonts',
    author: 'Vernon Adams',
    description: 'A fun, bold brush script script inspired by 1950s American surf culture.',
    arabicDescription: 'خط فرشاه مرح وجريء مستوحى من ثقافة ركوب الأمواج الأمريكية في الخمسينيات.',
    recommendedUse: 'Casual logos, food packaging, youth brands.',
    arabicRecommendedUse: 'الشعارات غير الرسمية، تعبئة وتغليف الأطعمة، الماركات الشبابية.'
  },
  {
    id: 'birthstone-bounce',
    name: 'Birthstone Bounce',
    arabicCategory: 'خط رشيق وراقص',
    category: 'script',
    family: '"Birthstone Bounce", cursive',
    source: 'Google Fonts',
    author: 'Robert Leuschke',
    description: 'A vibrant, bouncy calligraphic script with playful rhythm and high elegance.',
    arabicDescription: 'خط كاليغرافي نابض بالحياة وراقص مع إيقاع مرح ورشاقة تعبيرية عالية.',
    recommendedUse: 'Creative arts, feminine brands, custom fashion items.',
    arabicRecommendedUse: 'الفنون الإبداعية، الماركات النسائية الرقيقة، وتصاميم الموضة.'
  },
  {
    id: 'alex-brush',
    name: 'Alex Brush',
    arabicCategory: 'خط فرشاة كلاسيكي وقصير',
    category: 'script',
    family: '"Alex Brush", cursive',
    source: 'Google Fonts',
    author: 'TypeSETit',
    description: 'A classic brush script with short climbers, ensuring extremely neat legibility.',
    arabicDescription: 'خط فرشاة كلاسيكي يتميز بقصر ارتفاعات الحروف، مما يضمن وضوحاً فائقاً وسهلاً للقراءة.',
    recommendedUse: 'Subtitles, certification titles, refined headers.',
    arabicRecommendedUse: 'العناوين الفرعية، شهادات التقدير، والترويسات الرفيعة.'
  },
  {
    id: 'rochester',
    name: 'Rochester',
    arabicCategory: 'خط أرت ديكو فيكتوري',
    category: 'script',
    family: '"Rochester", cursive',
    source: 'Google Fonts',
    author: 'Sideshow',
    description: 'An elegant vintage script inspired by Victorian and Art Deco commercial art.',
    arabicDescription: 'خط كلاسيكي فاخر مستوحى من الفن الفيكتوري التجاري وأسلوب الأرت ديكو العريق.',
    recommendedUse: 'Fine dining menus, boutique logos, historic branding.',
    arabicRecommendedUse: 'قوائم المطاعم الفاخرة، شعارات البوتيك، والهويات التاريخية.'
  },
  {
    id: 'allura',
    name: 'Allura',
    arabicCategory: 'خط يد ناعم وفنيّ',
    category: 'script',
    family: '"Allura", cursive',
    source: 'Google Fonts',
    author: 'TypeSETit',
    description: 'Stylized yet highly legible, Allura is soft, flowing and incredibly diverse.',
    arabicDescription: 'خط فني خلاب وسهل القراءة للغاية، ناعم وانسيابي ومرغوب جداً في التصاميم الرومانسية.',
    recommendedUse: 'Invitations, premium cosmetics, stationery layout.',
    arabicRecommendedUse: 'بطاقات الدعوة، مستحضرات التجميل الممتازة، والأدوات المكتبية.'
  },
  {
    id: 'pinyon-script',
    name: 'Pinyon Script',
    arabicCategory: 'خط أرستقراطي فخم',
    category: 'script',
    family: '"Pinyon Script", cursive',
    source: 'Google Fonts',
    author: 'Nicole Fally',
    description: 'An elegant round-hand script with dramatic slants, oozing high aristocratic prestige.',
    arabicDescription: 'خط يدوي دائري أنيق مع ميلان درامي ساحر، يوحي بالرقي الأرستقراطي والفخامة المطلقة.',
    recommendedUse: 'Wine labels, hotel branding, royal certificates.',
    arabicRecommendedUse: 'ملصقات النبيذ والمنتجات الفاخرة، فنادق 5 نجوم، والوثائق الرسمية.'
  },
  {
    id: 'parisienne',
    name: 'Parisienne',
    arabicCategory: 'خط باريسي ناعم',
    category: 'script',
    family: '"Parisienne", cursive',
    source: 'Google Fonts',
    author: 'Astigmatic',
    description: 'A charming, bouncy script that is both casual and formal with a French flair.',
    arabicDescription: 'خط ساحر وراقص يجمع بين الرسمية والعفوية بلمسة فرنسية باريسية ساحرة.',
    recommendedUse: 'Fashion blogs, vintage luxury cards, cosmetics packaging.',
    arabicRecommendedUse: 'مدونات الموضة، بطاقات الهدايا الفاخرة، وتغليف العطور.'
  },
  {
    id: 'tangerine',
    name: 'Tangerine',
    arabicCategory: 'خط مائل طويل الحواف',
    category: 'script',
    family: '"Tangerine", cursive',
    source: 'Google Fonts',
    author: 'Toshi Omagari',
    description: 'A tall chancery cursive style with elegant thin lines and majestic sweeps.',
    arabicDescription: 'طراز خط مكتبة تاريخي طويل مع خطوط رفيعة رشيقة وامتدادات مهيبة للحروف.',
    recommendedUse: 'Poetic titles, large display quotes, certificate bodies.',
    arabicRecommendedUse: 'العناوين الشعرية، الاقتباسات الكبيرة، والشهادات ذات الطابع التاريخي.'
  },

  // --- SERIFS (Elegant Editorial & Modern Roman) ---
  {
    id: 'playfair-display',
    name: 'Playfair Display',
    arabicCategory: 'سيريف تحريري فخم',
    category: 'serif',
    family: '"Playfair Display", serif',
    source: 'Google Fonts',
    author: 'Claus Eggers Sørensen',
    description: 'High-contrast editorial serif, perfect for dramatic, modern-classic layouts.',
    arabicDescription: 'خط سيريف ذو تباين عالٍ وأنيق للغاية، ممتاز لتصاميم المجلات والعناوين الكلاسيكية والحديثة.',
    recommendedUse: 'Fashion magazines, upscale agency logos, editorial design.',
    arabicRecommendedUse: 'مجلات الموضة والأزياء، شعارات الوكالات الراقية، والتصاميم التحريرية.'
  },
  {
    id: 'cormorant-garamond',
    name: 'Cormorant Garamond',
    arabicCategory: 'غاراموند كلاسيكي ورفيع',
    category: 'serif',
    family: '"Cormorant Garamond", serif',
    source: 'Google Fonts',
    author: 'Christian Thalmann',
    description: 'Extremely refined and crisp representation of classic Garamond letterforms.',
    arabicDescription: 'تصميم نقي ودقيق للغاية ومصقول لخط غاراموند الكلاسيكي الخالد بلمسات تناسب العصر.',
    recommendedUse: 'Fine-art headings, luxury perfume styling, poetry.',
    arabicRecommendedUse: 'عناوين الفنون الجميلة، شعارات عطور النخبة، والإنتاج الأدبي.'
  },
  {
    id: 'cinzel',
    name: 'Cinzel',
    arabicCategory: 'خط روماني قديم مهيب',
    category: 'serif',
    family: '"Cinzel", serif',
    source: 'Google Fonts',
    author: 'Natanael Gama',
    description: 'Inspired by ancient Roman inscriptions, classical and majestic letterforms.',
    arabicDescription: 'مستوحى من النقوش الإمبراطورية الرومانية القديمة، ذو حروف كلاسيكية مهيبة وفخمة.',
    recommendedUse: 'Cinematic titles, institutional prestige, luxury hotel branding.',
    arabicRecommendedUse: 'العناوين السينمائية، شعارات الهيئات المرموقة، والفنادق الكبرى.'
  },
  {
    id: 'cinzel-decorative',
    name: 'Cinzel Decorative',
    arabicCategory: 'روماني مزخرف فخم',
    category: 'serif',
    family: '"Cinzel Decorative", serif',
    source: 'Google Fonts',
    author: 'Natanael Gama',
    description: 'Swashes and elegant ornamental extensions added to the Roman grandeur of Cinzel.',
    arabicDescription: 'يضيف تموجات وزخارف إضافية رائعة لحروف خط "Cinzel" الرومانية لزيادة البهاء والتفرد.',
    recommendedUse: 'Jewelry boutiques, fantasy branding, initials & seals.',
    arabicRecommendedUse: 'محلات المجوهرات الفاخرة، هويات الروايات والقصص، الحروف الأحادية والأختام.'
  },
  {
    id: 'bodoni-moda',
    name: 'Bodoni Moda',
    arabicCategory: 'سيريف إيطالي تباين مطلق',
    category: 'serif',
    family: '"Bodoni Moda", serif',
    source: 'Google Fonts',
    author: 'Owen Earl',
    description: 'A digital masterpiece of Bodoni, featuring extreme hair-line contrast for high couture.',
    arabicDescription: 'تحفة رقمية لخط بودوني الإيطالي الإمبراطوري، يتميز بتباين مذهل ورائع لبيوت الأزياء والموضة.',
    recommendedUse: 'High couture logos, runway magazines, art gallery headings.',
    arabicRecommendedUse: 'تصاميم الأزياء الراقية، مجلات الموضة، وعناوين المعارض الفنية.'
  },
  {
    id: 'prata',
    name: 'Prata',
    arabicCategory: 'سيريف ناعم ومتناسق',
    category: 'serif',
    family: '"Prata", serif',
    source: 'Google Fonts',
    author: 'Cyreal',
    description: 'Elegant didone serif with drop-shaped terminals and soft teardrop curves.',
    arabicDescription: 'خط سيريف ديدون أنيق وجميل للغاية بنهايات دائرية على شكل قطرات ناعمة ومتسقة.',
    recommendedUse: 'Cosmetics branding, wedding stationary, magazine columns.',
    arabicRecommendedUse: 'العلامات التجارية لعلامات العناية بالبشرة، تفاصيل الزفاف، وأعمدة المجلات.'
  },
  {
    id: 'fraunces',
    name: 'Fraunces',
    arabicCategory: 'سيريف طيني عتيق ودافئ',
    category: 'serif',
    family: '"Fraunces", serif',
    source: 'Google Fonts',
    author: 'Undercase Type',
    description: 'A charming, organic variable serif with expressive soft curves and warm voice.',
    arabicDescription: 'خط سيريف دافئ وعضوي وساحر للغاية يتميز بمنحنيات مريحة وتصميم فني فريد.',
    recommendedUse: 'Artisan cafes, coffee roasters, hand-crafted goods packaging.',
    arabicRecommendedUse: 'المقاهي المتخصصة، محامص القهوة، وهويات المنتجات الحرفية اليدوية.'
  },
  {
    id: 'eb-garamond',
    name: 'EB Garamond',
    arabicCategory: 'الخط الأكاديمي التاريخي',
    category: 'serif',
    family: '"EB Garamond", serif',
    source: 'Google Fonts',
    author: 'Georg Duffner',
    description: 'The standard of classical literature, reflecting academic prestige and longevity.',
    arabicDescription: 'المعيار الذهبي للأدب الكلاسيكي والكتب المرموقة، يعكس العراقة والاستمرارية التاريخية.',
    recommendedUse: 'Book publishing, law firm logos, academic certificates.',
    arabicRecommendedUse: 'دور النشر الأكاديمية والكتب، مكاتب المحاماة المرموقة، والشهادات العلمية.'
  },

  // --- BRUTALIST & BOLD DISPLAY (Logo types from the image) ---
  {
    id: 'archivo-black',
    name: 'Archivo Black',
    arabicCategory: 'سوبر جريء صناعي عريض',
    category: 'display',
    family: '"Archivo Black", sans-serif',
    source: 'Google Fonts',
    author: 'Omnibus-Type',
    description: 'A massive, high-impact sans designed for bold industrial headlines.',
    arabicDescription: 'خط ضخم وعريض جداً ذو تأثير بصري هائل، مصمم خصيصاً للعناوين الصناعية الجريئة.',
    recommendedUse: 'Posters, heavy apparel logos, loud headlines.',
    arabicRecommendedUse: 'البوسترات الضخمة، شعارات الملابس الثقيلة، والعناوين الصارخة.'
  },
  {
    id: 'anton',
    name: 'Anton',
    arabicCategory: 'جريء مضغوط عمودي',
    category: 'display',
    family: '"Anton", sans-serif',
    source: 'Google Fonts',
    author: 'Vernon Adams',
    description: 'A heavy, vertically compressed display font with extreme presence.',
    arabicDescription: 'خط عرض ثقيل ومضغوط رأسياً يمنح الكلمات حضوراً وقوة جذب فورية لا تصدق.',
    recommendedUse: 'Dynamic advertising, sports logos, gym banners.',
    arabicRecommendedUse: 'الإعلانات الديناميكية، الشعارات الرياضية، لافتات صالات الألعاب الرياضية.'
  },
  {
    id: 'righteous',
    name: 'Righteous',
    arabicCategory: 'هندسي فنكو-ريترو ديدون',
    category: 'display',
    family: '"Righteous", sans-serif',
    source: 'Google Fonts',
    author: 'Astigmatic',
    description: 'A stylized geometry font inspired by the 1980s retro-wave and synth culture.',
    arabicDescription: 'خط هندسي فني رائع مستوحى من ثقافة ريترو-ويف والإلكترونيات في الثمانينيات.',
    recommendedUse: 'Gaming studios, tech startups, synthwave themes.',
    arabicRecommendedUse: 'أستوديوهات الألعاب، الشركات الناشئة المبتكرة، وثقافات المستقبل ريترو.'
  },
  {
    id: 'oswald',
    name: 'Oswald',
    arabicCategory: 'كلاسيكي ضيق ومستقر',
    category: 'display',
    family: '"Oswald", sans-serif',
    source: 'Google Fonts',
    author: 'Vernon Adams',
    description: 'A reimagined classic gothic style, highly professional and solid.',
    arabicDescription: 'إعادة تصور للخط الغوطي الكلاسيكي، مضغوط بعناية وممتاز لتنظيم المحتوى الإعلاني.',
    recommendedUse: 'News headings, corporate badges, solid labels.',
    arabicRecommendedUse: 'عناوين الأخبار، بطاقات الشركات الرسمية، والملصقات الصلبة.'
  },
  {
    id: 'syne',
    name: 'Syne',
    arabicCategory: 'بروتاليست متطور فنيّ',
    category: 'display',
    family: '"Syne", sans-serif',
    source: 'Google Fonts',
    author: 'Bonjour Monde',
    description: 'Extremely creative geometric design, stretching into wider tech forms.',
    arabicDescription: 'تصميم هندسي مبتكر يمتد للاتساع في أوزانه الثقيلة ليعكس فلسفة فنية حديثة وطليعية.',
    recommendedUse: 'Modern art studios, high-tech branding, creative flyers.',
    arabicRecommendedUse: 'أستوديوهات الفن الحديث، الهويات التقنية المعاصرة، والنشرات الإبداعية.'
  },
  {
    id: 'unbounded',
    name: 'Unbounded',
    arabicCategory: 'عريض للغاية مستقبلي',
    category: 'display',
    family: '"Unbounded", sans-serif',
    source: 'Google Fonts',
    author: 'Font Bureau',
    description: 'Extravagantly wide, blocky modern display font with incredible tech styling.',
    arabicDescription: 'خط مستقبلي عريض جداً ذو زوايا جريئة ومظهر تقني مذهل يلائم العصر الرقمي المتطور.',
    recommendedUse: 'E-sports branding, cryptocurrency layouts, extreme tech.',
    arabicRecommendedUse: 'رياضات ألعاب الفيديو الإلكترونية، العملات المشفرة، والتقنيات المستقبلية.'
  },

  // --- MODERN MINIMALIST SANS-SERIFS ---
  {
    id: 'inter',
    name: 'Inter',
    arabicCategory: 'هادئ مكسيكي غيوم',
    category: 'sans-serif',
    family: '"Inter", sans-serif',
    source: 'Google Fonts',
    author: 'Rasmus Andersson',
    description: 'The global standard for premium, elegant, crystal-clear user interfaces.',
    arabicDescription: 'المعيار العالمي السائد لواجهات الاستخدام الفاخرة والنقية والسهلة للقراءة والتصفح.',
    recommendedUse: 'Perfect UI copy, secondary text, metadata.',
    arabicRecommendedUse: 'نصوص واجهة المستخدم، العناوين الفرعية الدقيقة، والبيانات المساعدة.'
  },
  {
    id: 'plus-jakarta-sans',
    name: 'Plus Jakarta Sans',
    arabicCategory: 'سنز هندسي دافئ معتدل',
    category: 'sans-serif',
    family: '"Plus Jakarta Sans", sans-serif',
    source: 'Google Fonts',
    author: 'Tokotype',
    description: 'A beautiful, clean geometric sans-serif with a warm active tone.',
    arabicDescription: 'خط هندسي معاصر ونقي للغاية بلمسات دافئة تمنح التصميم الحيوية والجاذبية الحديثة.',
    recommendedUse: 'Startup landing pages, corporate copy, clean app interface.',
    arabicRecommendedUse: 'صفحات الهبوط للشركات الناشئة، النصوص المؤسسية، وواجهات التطبيقات الحديثة.'
  },
  {
    id: 'dm-sans',
    name: 'DM Sans',
    arabicCategory: 'هندسي نقي واحترافي',
    category: 'sans-serif',
    family: '"DM Sans", sans-serif',
    source: 'Google Fonts',
    author: 'Colophon Foundry',
    description: 'A low-contrast geometric sans serif intended for robust scaling and clean layout.',
    arabicDescription: 'خط هندسي منخفض التباين ومصمم للعمل بكفاءة تامة عبر أحجام العرض المختلفة وبكل ثقة.',
    recommendedUse: 'Digital magazines, minimal branding, clean captions.',
    arabicRecommendedUse: 'المجلات الرقمية، الشعارات التبسيطية، والشروحات والنصوص الثانوية النظيفة.'
  },
  {
    id: 'fira-code',
    name: 'Fira Code',
    arabicCategory: 'خط مونو تكنولوجي حاد',
    category: 'monospace',
    family: '"Fira Code", monospace',
    source: 'Google Fonts',
    author: 'Nikita Prokopov',
    description: 'A monospaced font with programming ligatures, perfect for technical overlays and tags.',
    arabicDescription: 'خط مونو مخصص للمبرمجين مع علامات برمجية متصلة، مثالي للشعارات التقنية والصناعية الحديثة.',
    recommendedUse: 'Technical tags, metadata overlays, modern industrial badges.',
    arabicRecommendedUse: 'البطاقات التقنية، شاشات البيانات الفنية، والملصقات الصناعية الحديثة.'
  },
  {
    id: 'jetbrains-mono',
    name: 'JetBrains Mono',
    arabicCategory: 'خط مونو هندسي نقي',
    category: 'monospace',
    family: '"JetBrains Mono", monospace',
    source: 'Google Fonts',
    author: 'JetBrains',
    description: 'An exceptionally clean, highly-readable monospaced font built for code and system UI.',
    arabicDescription: 'خط ذو مسافات بادئة متساوية يتميز بوضوح استثنائي صُمم خصيصاً للتطبيقات والواجهات البرمجية.',
    recommendedUse: 'System telemetry, clean subtitle tags, serial-number graphics.',
    arabicRecommendedUse: 'البيانات البرمجية، الوسوم والتسميات الفنية، وخطوط الأرقام التسلسلية والشارات.'
  },
  {
    id: 'montserrat',
    name: 'Montserrat',
    arabicCategory: 'خط سنز جريء ونظيف',
    category: 'sans-serif',
    family: '"Montserrat", sans-serif',
    source: 'Google Fonts',
    author: 'Julieta Ulanovsky',
    description: 'A highly functional geometric sans-serif inspired by old posters in Buenos Aires.',
    arabicDescription: 'خط سنز هندسي عملي للغاية وممتاز مستوحى من ملصقات اللوحات الحضرية القديمة لبيونس آيرس.',
    recommendedUse: 'Bold branding, impactful secondary titles, clean contemporary text.',
    arabicRecommendedUse: 'العلامات التجارية الجريئة، العناوين الفرعية المؤثرة، والنصوص المعاصرة النظيفة.'
  },
  {
    id: 'outfit',
    name: 'Outfit',
    arabicCategory: 'خط سنز هندسي عصري فائق الجمال',
    category: 'sans-serif',
    family: '"Outfit", sans-serif',
    source: 'Google Fonts',
    author: 'Outfit Studio',
    description: 'A beautifully balanced, warm and modern geometric sans-serif font family.',
    arabicDescription: 'عائلة خطوط هندسية متوازنة ورائعة للغاية تعكس الحداثة والجمال والدقة البصرية الفائقة.',
    recommendedUse: 'Tech websites, minimalist displays, clean interface copy.',
    arabicRecommendedUse: 'مواقع التقنية والابتكار، شاشات العرض المينيمال، نصوص الواجهات الحديثة.'
  },
  {
    id: 'playball',
    name: 'Playball',
    arabicCategory: 'خط رياضي متصل ورشيق',
    category: 'script',
    family: '"Playball", cursive',
    source: 'Google Fonts',
    author: 'TypeSETit',
    description: 'A festive, athletic script with a beautiful cursive flow and sturdy presence.',
    arabicDescription: 'خط متصل رياضي ذو طابع احتفالي يتميز بجريانه الانسيابي الأنيق وحضوره القوي.',
    recommendedUse: 'Sporting goods branding, casual restaurant logos, invitations.',
    arabicRecommendedUse: 'هويات السلع الرياضية، شعارات المقاهي غير الرسمية، وبطاقات الدعوة.'
  },
  {
    id: 'share-tech-mono',
    name: 'Share Tech Mono',
    arabicCategory: 'خط مونو السيبراني المستقبلي',
    category: 'monospace',
    family: '"Share Tech Mono", monospace',
    source: 'Google Fonts',
    author: 'Carrois Apostrophe',
    description: 'A tech-forward digital font built for cybernetic interfaces and coding aesthetics.',
    arabicDescription: 'خط رقمي ذو طابع مستقبلي مخصص للواجهات السيبرانية وجماليات الأكواد والبيانات الرقمية.',
    recommendedUse: 'Tech interfaces, cyber labels, digital displays.',
    arabicRecommendedUse: 'الواجهات التقنية والوسوم السيبرانية، شاشات العرض الرقمية المشفرة.'
  },
  {
    id: 'space-grotesk',
    name: 'Space Grotesk',
    arabicCategory: 'خط هندسي عصري حاد ومميز',
    category: 'sans-serif',
    family: '"Space Grotesk", sans-serif',
    source: 'Google Fonts',
    author: 'Florian Karsten',
    description: 'A striking sans-serif with subtle quirky details, great for headlines and display text.',
    arabicDescription: 'خط سنز متميز ملفت للغاية مع ثنيات فنية جذابة، غاية في الجمال للعناوين والنصوص الإعلانية.',
    recommendedUse: 'Agency branding, quirky tech captions, futuristic headlines.',
    arabicRecommendedUse: 'شعارات الوكالات الإبداعية، وسوم الشروحات الفنية، والعناوين المستقبلية.'
  },
  {
    id: 'space-mono',
    name: 'Space Mono',
    arabicCategory: 'خط مونو تكنولوجي كلاسيكي للمستقبل',
    category: 'monospace',
    family: '"Space Mono", monospace',
    source: 'Google Fonts',
    author: 'Editorial New',
    description: 'A geometric monospaced typeface ideal for tech layouts, digital badges, and labels.',
    arabicDescription: 'خط مونو هندسي رائع مثالي للتصاميم التقنية، والشارات الرقمية، والملصقات التعبيرية.',
    recommendedUse: 'Retro-tech designs, catalog numbers, digital badges.',
    arabicRecommendedUse: 'تصاميم التكنولوجيا العتيقة (ريترو)، أرقام الكتالوغات، والشارات الرقمية.'
  }
];

const excludeIds = new Set(BASE_FONTS.map(f => f.id));
export const FONTS_CATALOG: FontItem[] = [...BASE_FONTS, ...getExtraFonts(excludeIds)];

export const PRESETS_CATALOG: LogoPreset[] = [
  // --- ROW 1 ---
  {
    id: 'preset-audio',
    presetName: 'AUDIO',
    arabicPresetName: 'شعار AUDIO الرياضي العريض',
    title: 'AUDIO',
    arabicTitle: 'أوديو ستوديو',
    mainText: 'AUDIO',
    subtitleText: 'LIMITED APPAREL = ',
    mainFontId: 'archivo-black',
    mainStyle: { text: 'AUDIO', fontSize: 85, fontWeight: 900, letterSpacing: 0.1, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'space-mono',
    subtitleStyle: { text: 'LIMITED APPAREL = ', fontSize: 12, fontWeight: 605, letterSpacing: 0.2, uppercase: true, italic: true, fontFamily: '"Space Mono", monospace', visible: true, opacity: 0.8 },
    bgColor: '#0a0a0a', textColor: '#ffffff', accentColor: '#e5e5e5',
    bgConfig: { type: 'solid', colorStart: '#0a0a0a', colorEnd: '#171717', angle: 180 },
    borderType: 'accent-line', category: 'display', row: 1
  },
  {
    id: 'preset-hunt',
    presetName: 'HUNT & COM',
    arabicPresetName: 'شعار HUNT للصحافة والنشر',
    title: 'HUNT & COM',
    arabicTitle: 'هانت آند كوم',
    mainText: 'HUNT & COM',
    subtitleText: '— magazine —',
    mainFontId: 'cinzel',
    mainStyle: { text: 'HUNT & COM', fontSize: 62, fontWeight: 700, letterSpacing: 0.08, lineHeight: 1.1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'playfair-display',
    subtitleStyle: { text: '— magazine —', fontSize: 14, fontWeight: 400, letterSpacing: 0.35, uppercase: false, italic: true, fontFamily: '"Playfair Display", serif', visible: true, opacity: 0.75 },
    bgColor: '#161514', textColor: '#fafaf9', accentColor: '#d6d3d1',
    bgConfig: { type: 'gradient', colorStart: '#161514', colorEnd: '#0a0a0a', angle: 135 },
    borderType: 'none', category: 'serif', row: 1
  },
  {
    id: 'preset-glamour',
    presetName: 'Glamour faith',
    arabicPresetName: 'شعار Glamour faith العتيق الفاخر',
    title: 'Glamour faith',
    arabicTitle: 'بريق الإيمان',
    mainText: 'Glamour faith',
    subtitleText: 'Vintage Apparel | London',
    mainFontId: 'great-vibes',
    mainStyle: { text: 'Glamour faith', fontSize: 88, fontWeight: 400, letterSpacing: 0.02, lineHeight: 1.2, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'plus-jakarta-sans',
    subtitleStyle: { text: 'Vintage Apparel | London', fontSize: 11, fontWeight: 500, letterSpacing: 0.2, uppercase: true, italic: false, fontFamily: '"Plus Jakarta Sans", sans-serif', visible: true, opacity: 0.7 },
    bgColor: '#141111', textColor: '#fbf5eb', accentColor: '#c5a88a',
    bgConfig: { type: 'radial', colorStart: '#1c1515', colorEnd: '#0d0a0a', angle: 180 },
    borderType: 'rounded', category: 'script', row: 1
  },
  {
    id: 'preset-kloning',
    presetName: 'Kloning',
    arabicPresetName: 'شعار Kloning اليدوي الراقي',
    title: 'Kloning',
    arabicTitle: 'كلونينج للمؤسسات',
    mainText: 'Kloning',
    subtitleText: 'O R G A N I Z A T I O N',
    mainFontId: 'sacramento',
    mainStyle: { text: 'Kloning', fontSize: 90, fontWeight: 500, letterSpacing: 0.05, lineHeight: 1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'O R G A N I Z A T I O N', fontSize: 10, fontWeight: 700, letterSpacing: 0.4, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.8 },
    bgColor: '#0f1115', textColor: '#ffffff', accentColor: '#38bdf8',
    bgConfig: { type: 'gradient', colorStart: '#111827', colorEnd: '#030712', angle: 135 },
    borderType: 'none', category: 'script', row: 1
  },

  // --- ROW 2 ---
  {
    id: 'preset-antartica',
    presetName: 'Antartica',
    arabicPresetName: 'شعار Antartica للمقاهي والكتب',
    title: 'Antartica',
    arabicTitle: 'أنتارتيكا كافيه',
    mainText: 'Antartica',
    subtitleText: 'CAFE & BOOK STORE',
    mainFontId: 'pacifico',
    mainStyle: { text: 'Antartica', fontSize: 75, fontWeight: 400, letterSpacing: 0, lineHeight: 1.2, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'plus-jakarta-sans',
    subtitleStyle: { text: 'CAFE & BOOK STORE', fontSize: 11, fontWeight: 600, letterSpacing: 0.25, uppercase: true, italic: false, fontFamily: '"Plus Jakarta Sans", sans-serif', visible: true, opacity: 0.75 },
    bgColor: '#0f172a', textColor: '#e2e8f0', accentColor: '#38bdf8',
    bgConfig: { type: 'gradient', colorStart: '#0f172a', colorEnd: '#020617', angle: 180 },
    borderType: 'thin', category: 'script', row: 2
  },
  {
    id: 'preset-superguts',
    presetName: 'SUPER GUTS',
    arabicPresetName: 'شعار SUPER GUTS الصناعي الجريء',
    title: 'SUPER GUTS',
    arabicTitle: 'سوبر غاتس للخدمات',
    mainText: 'SUPER GUTS',
    subtitleText: '• General Service •',
    mainFontId: 'archivo-black',
    mainStyle: { text: 'SUPER GUTS', fontSize: 62, fontWeight: 900, letterSpacing: 0.05, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'space-mono',
    subtitleStyle: { text: '• General Service •', fontSize: 12, fontWeight: 400, letterSpacing: 0.2, uppercase: true, italic: true, fontFamily: '"Space Mono", monospace', visible: true, opacity: 0.8 },
    bgColor: '#171717', textColor: '#ffffff', accentColor: '#f59e0b',
    bgConfig: { type: 'solid', colorStart: '#171717', colorEnd: '#262626', angle: 90 },
    borderType: 'accent-line', category: 'display', row: 2
  },
  {
    id: 'preset-jeatlopz',
    presetName: 'Jeatlopz',
    arabicPresetName: 'شعار Jeatlopz الفني التعبيري',
    title: 'Jeatlopz',
    arabicTitle: 'جيتلوبز للمستكشفين',
    mainText: 'Jeatlopz',
    subtitleText: '— F I N D E R —',
    mainFontId: 'windsong',
    mainStyle: { text: 'Jeatlopz', fontSize: 105, fontWeight: 500, letterSpacing: 0, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: '— F I N D E R —', fontSize: 11, fontWeight: 700, letterSpacing: 0.3, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.9 },
    bgColor: '#1c1917', textColor: '#f5f5f4', accentColor: '#e7e5e4',
    bgConfig: { type: 'gradient', colorStart: '#1c1917', colorEnd: '#0c0a09', angle: 180 },
    borderType: 'none', category: 'script', row: 2
  },
  {
    id: 'preset-cargo',
    presetName: 'CARGO',
    arabicPresetName: 'شعار CARGO اللوجستي العريض',
    title: 'CARGO',
    arabicTitle: 'كارغو للمقاييس',
    mainText: 'CARGO',
    subtitleText: '— metrics —',
    mainFontId: 'space-grotesk',
    mainStyle: { text: 'CARGO', fontSize: 70, fontWeight: 700, letterSpacing: 0.15, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'jetbrains-mono',
    subtitleStyle: { text: '— metrics —', fontSize: 11, fontWeight: 500, letterSpacing: 0.25, uppercase: true, italic: false, fontFamily: '"JetBrains Mono", monospace', visible: true, opacity: 0.8 },
    bgColor: '#09090b', textColor: '#fafafa', accentColor: '#a1a1aa',
    bgConfig: { type: 'solid', colorStart: '#09090b', colorEnd: '#1e1b4b', angle: 180 },
    borderType: 'none', category: 'sans', row: 2
  },
  {
    id: 'preset-oxy',
    presetName: 'Oxy CO.',
    arabicPresetName: 'شعار Oxy CO. الدائري البسيط',
    title: 'Oxy CO.',
    arabicTitle: 'أوكسي المحدودة',
    mainText: 'Oxy',
    subtitleText: 'CO.',
    mainFontId: 'pacifico',
    mainStyle: { text: 'Oxy', fontSize: 80, fontWeight: 400, letterSpacing: -0.02, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'space-grotesk',
    subtitleStyle: { text: 'CO.', fontSize: 13, fontWeight: 800, letterSpacing: 0.1, uppercase: true, italic: false, fontFamily: '"Space Grotesk", sans-serif', visible: true, opacity: 0.9 },
    bgColor: '#18181b', textColor: '#ffffff', accentColor: '#facc15',
    bgConfig: { type: 'radial', colorStart: '#27272a', colorEnd: '#09090b', angle: 180 },
    borderType: 'rounded', category: 'script', row: 2
  },

  // --- ROW 3 ---
  {
    id: 'preset-borcop',
    presetName: 'BORCOP',
    arabicPresetName: 'شعار BORCOP الهندسي الهيكلي',
    title: 'BORCOP',
    arabicTitle: 'بوركوب للمستقبل',
    mainText: 'BORCOP',
    subtitleText: 'Remachine',
    mainFontId: 'archivo-black',
    mainStyle: { text: 'BORCOP', fontSize: 75, fontWeight: 900, letterSpacing: 0.08, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'great-vibes',
    subtitleStyle: { text: 'Remachine', fontSize: 24, fontWeight: 400, letterSpacing: 0.05, uppercase: false, italic: false, fontFamily: '"Great Vibes", cursive', visible: true, opacity: 0.95 },
    bgColor: '#0c0a09', textColor: '#ffffff', accentColor: '#ea580c',
    bgConfig: { type: 'solid', colorStart: '#0c0a09', colorEnd: '#1c1917', angle: 180 },
    borderType: 'none', category: 'display', row: 3
  },
  {
    id: 'preset-metr',
    presetName: 'MetR',
    arabicPresetName: 'شعار MetR التكنولوجي المبتكر',
    title: 'MetR',
    arabicTitle: 'ميتر للرموز المجانية',
    mainText: 'MetR',
    subtitleText: 'FREE Stock Icon',
    mainFontId: 'space-grotesk',
    mainStyle: { text: 'MetR', fontSize: 82, fontWeight: 600, letterSpacing: -0.02, lineHeight: 1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'jetbrains-mono',
    subtitleStyle: { text: 'FREE Stock Icon', fontSize: 11, fontWeight: 400, letterSpacing: 0.15, uppercase: true, italic: false, fontFamily: '"JetBrains Mono", monospace', visible: true, opacity: 0.7 },
    bgColor: '#0b1329', textColor: '#ffffff', accentColor: '#38bdf8',
    bgConfig: { type: 'gradient', colorStart: '#0f172a', colorEnd: '#020617', angle: 135 },
    borderType: 'rounded', category: 'sans', row: 3
  },
  {
    id: 'preset-masterplans',
    presetName: 'Masterplans',
    arabicPresetName: 'شعار Masterplans التجاري الأنيق',
    title: 'Masterplans',
    arabicTitle: 'مخططات ريادية',
    mainText: 'Masterplans',
    subtitleText: 'BUSINESS / MARKETING',
    mainFontId: 'tangerine',
    mainStyle: { text: 'Masterplans', fontSize: 110, fontWeight: 400, letterSpacing: 0.03, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'plus-jakarta-sans',
    subtitleStyle: { text: 'BUSINESS / MARKETING', fontSize: 10, fontWeight: 700, letterSpacing: 0.3, uppercase: true, italic: false, fontFamily: '"Plus Jakarta Sans", sans-serif', visible: true, opacity: 0.8 },
    bgColor: '#1c1917', textColor: '#fafaf9', accentColor: '#d6d3d1',
    bgConfig: { type: 'solid', colorStart: '#1c1917', colorEnd: '#0c0a09', angle: 180 },
    borderType: 'none', category: 'script', row: 3
  },
  {
    id: 'preset-hurlex',
    presetName: 'HURLEX',
    arabicPresetName: 'شعار HURLEX المستقبلي الممتد',
    title: 'HURLEX',
    arabicTitle: 'هيرليكس للأزياء',
    mainText: 'HURLEX',
    subtitleText: 'A P P A R E L',
    mainFontId: 'unbounded',
    mainStyle: { text: 'HURLEX', fontSize: 55, fontWeight: 800, letterSpacing: 0.12, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'A P P A R E L', fontSize: 10, fontWeight: 600, letterSpacing: 0.5, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.75 },
    bgColor: '#09090b', textColor: '#fafafa', accentColor: '#e4e4e7',
    bgConfig: { type: 'solid', colorStart: '#09090b', colorEnd: '#1e1b4b', angle: 180 },
    borderType: 'accent-line', category: 'sans', row: 3
  },
  {
    id: 'preset-studio',
    presetName: 'Studio',
    arabicPresetName: 'شعار Studio الذهبي الملكي',
    title: 'Studio',
    arabicTitle: 'أستوديو الفنون',
    mainText: 'Studio',
    subtitleText: 'Golden Art',
    mainFontId: 'windsong',
    mainStyle: { text: 'Studio', fontSize: 115, fontWeight: 500, letterSpacing: 0.04, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'cinzel',
    subtitleStyle: { text: 'Golden Art', fontSize: 12, fontWeight: 800, letterSpacing: 0.4, uppercase: true, italic: false, fontFamily: '"Cinzel", serif', visible: true, opacity: 0.9 },
    bgColor: '#022c22', textColor: '#fbbf24', accentColor: '#fcd34d',
    bgConfig: { type: 'radial', colorStart: '#064e3b', colorEnd: '#022c22', angle: 180 },
    borderType: 'double', category: 'script', row: 3
  },

  // --- ROW 4 ---
  {
    id: 'preset-tacobell',
    presetName: 'TACOBELL',
    arabicPresetName: 'شعار TACOBELL للمأكولات السريعة والعريضة',
    title: 'TACOBELL',
    arabicTitle: 'تاكوبيل الأناقة',
    mainText: 'TACOBELL',
    subtitleText: 'supermaket',
    mainFontId: 'anton',
    mainStyle: { text: 'TACOBELL', fontSize: 75, fontWeight: 950, letterSpacing: 0.04, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'great-vibes',
    subtitleStyle: { text: 'supermaket', fontSize: 24, fontWeight: 450, letterSpacing: 0.05, uppercase: false, italic: false, fontFamily: '"Great Vibes", cursive', visible: true, opacity: 0.9 },
    bgColor: '#4a044e', textColor: '#fdf4ff', accentColor: '#f472b6',
    bgConfig: { type: 'solid', colorStart: '#4a044e', colorEnd: '#1f0022', angle: 180 },
    borderType: 'none', category: 'display', row: 4
  },
  {
    id: 'preset-onlinemag',
    presetName: 'online MAGAZINE',
    arabicPresetName: 'شعار online MAGAZINE الإبداعي المدمج',
    title: 'online MAGAZINE',
    arabicTitle: 'مجلة أونلاين',
    mainText: 'online',
    subtitleText: 'MAGAZINE',
    mainFontId: 'sacramento',
    mainStyle: { text: 'online', fontSize: 95, fontWeight: 400, letterSpacing: 0.02, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'MAGAZINE', fontSize: 16, fontWeight: 900, letterSpacing: 0.3, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.95 },
    bgColor: '#111', textColor: '#ffffff', accentColor: '#e5e5e5',
    bgConfig: { type: 'solid', colorStart: '#111', colorEnd: '#222', angle: 180 },
    borderType: 'none', category: 'display', row: 4
  },
  {
    id: 'preset-june',
    presetName: 'June',
    arabicPresetName: 'شعار June الفني الناعم المتصل',
    title: 'June',
    arabicTitle: 'يونيو للمجلات',
    mainText: 'June',
    subtitleText: 'MAGAZINE',
    mainFontId: 'alex-brush',
    mainStyle: { text: 'June', fontSize: 110, fontWeight: 400, letterSpacing: 0.05, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'space-mono',
    subtitleStyle: { text: 'MAGAZINE', fontSize: 11, fontWeight: 700, letterSpacing: 0.25, uppercase: true, italic: false, fontFamily: '"Space Mono", monospace', visible: true, opacity: 0.8 },
    bgColor: '#171717', textColor: '#fafafa', accentColor: '#d4d4d8',
    bgConfig: { type: 'solid', colorStart: '#171717', colorEnd: '#262626', angle: 180 },
    borderType: 'none', category: 'script', row: 4
  },
  {
    id: 'preset-cone',
    presetName: 'CONE',
    arabicPresetName: 'شعار CONE المؤسسي الهندسي',
    title: 'CONE',
    arabicTitle: 'مؤسسة كون المعمارية',
    mainText: 'CONE',
    subtitleText: 'COMPANY',
    mainFontId: 'plus-jakarta-sans',
    mainStyle: { text: 'CONE', fontSize: 75, fontWeight: 800, letterSpacing: 0.05, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'COMPANY', fontSize: 11, fontWeight: 600, letterSpacing: 0.35, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.85 },
    bgColor: '#0f172a', textColor: '#ffffff', accentColor: '#94a3b8',
    bgConfig: { type: 'gradient', colorStart: '#0f172a', colorEnd: '#020617', angle: 135 },
    borderType: 'thin', category: 'sans', row: 4
  },
  {
    id: 'preset-codered',
    presetName: 'CODE RED',
    arabicPresetName: 'شعار CODE RED التكنولوجي النيون',
    title: 'CODE RED',
    arabicTitle: 'كود ريد للتقنيات',
    mainText: 'CODE RED',
    subtitleText: 'public studio',
    mainFontId: 'unbounded',
    mainStyle: { text: 'CODE RED', fontSize: 54, fontWeight: 850, letterSpacing: 0.02, lineHeight: 1, uppercase: true, italic: false, textShadow: 'glow' },
    subtitleFontId: 'share-tech-mono',
    subtitleStyle: { text: 'public studio', fontSize: 12, fontWeight: 500, letterSpacing: 0.3, uppercase: false, italic: true, fontFamily: '"Share Tech Mono", monospace', visible: true, opacity: 0.9 },
    bgColor: '#0f0505', textColor: '#ef4444', accentColor: '#f87171',
    bgConfig: { type: 'grid', colorStart: '#0f0505', colorEnd: '#1e0808', angle: 180 },
    borderType: 'thin', category: 'display', row: 4
  },

  // --- ROW 5 ---
  {
    id: 'preset-shine',
    presetName: 'Shine',
    arabicPresetName: 'شعار Shine الفاخر للصناعات الخفيفة',
    title: 'Shine',
    arabicTitle: 'شمعة الإشراق',
    mainText: 'Shine',
    subtitleText: 'industrie',
    mainFontId: 'allura',
    mainStyle: { text: 'Shine', fontSize: 110, fontWeight: 400, letterSpacing: 0.05, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'jetbrains-mono',
    subtitleStyle: { text: 'industrie', fontSize: 11, fontWeight: 550, letterSpacing: 0.25, uppercase: true, italic: false, fontFamily: '"JetBrains Mono", monospace', visible: true, opacity: 0.75 },
    bgColor: '#1b1b1f', textColor: '#f8fafc', accentColor: '#cbd5e1',
    bgConfig: { type: 'gradient', colorStart: '#1e1b4b', colorEnd: '#09090b', angle: 135 },
    borderType: 'none', category: 'script', row: 5
  },
  {
    id: 'preset-unicorn',
    presetName: 'Unicorn',
    arabicPresetName: 'شعار Unicorn الساحر الأرستقراطي',
    title: 'Unicorn',
    arabicTitle: 'يونيكورن للنشر',
    mainText: 'Unicorn',
    subtitleText: 'PUBLISHER',
    mainFontId: 'parisienne',
    mainStyle: { text: 'Unicorn', fontSize: 100, fontWeight: 400, letterSpacing: 0.03, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'cinzel',
    subtitleStyle: { text: 'PUBLISHER', fontSize: 11, fontWeight: 700, letterSpacing: 0.35, uppercase: true, italic: false, fontFamily: '"Cinzel", serif', visible: true, opacity: 0.8 },
    bgColor: '#2e1065', textColor: '#fae8ff', accentColor: '#d8b4fe',
    bgConfig: { type: 'gradient', colorStart: '#2e1065', colorEnd: '#0f052d', angle: 135 },
    borderType: 'none', category: 'script', row: 5
  },
  {
    id: 'preset-oriental',
    presetName: 'ORIENTAL',
    arabicPresetName: 'شعار ORIENTAL الكلاسيكي العريق',
    title: 'ORIENTAL',
    arabicTitle: 'أورينتال للمنسوجات',
    mainText: 'ORIENTAL',
    subtitleText: 'LOCAL AGENCY',
    mainFontId: 'bodoni-moda',
    mainStyle: { text: 'ORIENTAL', fontSize: 62, fontWeight: 900, letterSpacing: 0.12, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'plus-jakarta-sans',
    subtitleStyle: { text: 'LOCAL AGENCY', fontSize: 10, fontWeight: 600, letterSpacing: 0.3, uppercase: true, italic: false, fontFamily: '"Plus Jakarta Sans", sans-serif', visible: true, opacity: 0.75 },
    bgColor: '#121212', textColor: '#fafaf9', accentColor: '#d6d3d1',
    bgConfig: { type: 'solid', colorStart: '#121212', colorEnd: '#1f2937', angle: 180 },
    borderType: 'accent-line', category: 'serif', row: 5
  },
  {
    id: 'preset-mute',
    presetName: 'Mute',
    arabicPresetName: 'شعار Mute البسيط المينيمال المتصل',
    title: 'Mute',
    arabicTitle: 'ميوت المخطط',
    mainText: 'Mute',
    subtitleText: 'planner',
    mainFontId: 'sacramento',
    mainStyle: { text: 'Mute', fontSize: 94, fontWeight: 400, letterSpacing: 0.02, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'jetbrains-mono',
    subtitleStyle: { text: 'planner', fontSize: 11, fontWeight: 400, letterSpacing: 0.25, uppercase: false, italic: true, fontFamily: '"JetBrains Mono", monospace', visible: true, opacity: 0.7 },
    bgColor: '#1c1917', textColor: '#fbfbfb', accentColor: '#e7e5e4',
    bgConfig: { type: 'solid', colorStart: '#1c1917', colorEnd: '#0a0a0a', angle: 180 },
    borderType: 'none', category: 'script', row: 5
  },
  {
    id: 'preset-lycan',
    presetName: 'Lycan',
    arabicPresetName: 'شعار Lycan الجريء المميز',
    title: 'Lycan',
    arabicTitle: 'لايكان للتطوير والمطورة',
    mainText: 'Lycan',
    subtitleText: 'corp.',
    mainFontId: 'birthstone-bounce',
    mainStyle: { text: 'Lycan', fontSize: 105, fontWeight: 700, letterSpacing: 0.02, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'space-mono',
    subtitleStyle: { text: 'corp.', fontSize: 12, fontWeight: 800, letterSpacing: 0.15, uppercase: true, italic: false, fontFamily: '"Space Mono", monospace', visible: true, opacity: 0.95 },
    bgColor: '#022c22', textColor: '#ffffff', accentColor: '#34d399',
    bgConfig: { type: 'radial', colorStart: '#064e3b', colorEnd: '#022c22', angle: 180 },
    borderType: 'rounded', category: 'script', row: 5
  },

  // --- ROW 6 ---
  {
    id: 'preset-hammer',
    presetName: 'Hammer',
    arabicPresetName: 'شعار Hammer للانتاج الفني والترفيه',
    title: 'Hammer',
    arabicTitle: 'المطرقة للإنتاج والترفيه',
    mainText: 'Hammer',
    subtitleText: 'ENTERTAINMENT',
    mainFontId: 'great-vibes',
    mainStyle: { text: 'Hammer', fontSize: 100, fontWeight: 450, letterSpacing: 0.02, lineHeight: 1.2, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'plus-jakarta-sans',
    subtitleStyle: { text: 'ENTERTAINMENT', fontSize: 11, fontWeight: 700, letterSpacing: 0.35, uppercase: true, italic: false, fontFamily: '"Plus Jakarta Sans", sans-serif', visible: true, opacity: 0.8 },
    bgColor: '#171717', textColor: '#ffffff', accentColor: '#e5e5e5',
    bgConfig: { type: 'solid', colorStart: '#171717', colorEnd: '#2d2d2d', angle: 180 },
    borderType: 'none', category: 'script', row: 6
  },
  {
    id: 'preset-barbel',
    presetName: 'Barbel',
    arabicPresetName: 'شعار Barbel للياقة وصالات الرياضة',
    title: 'Barbel',
    arabicTitle: 'باربيل للياقة البدنية',
    mainText: 'Barbel',
    subtitleText: 'super gym',
    mainFontId: 'pacifico',
    mainStyle: { text: 'Barbel', fontSize: 80, fontWeight: 550, letterSpacing: 0, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'super gym', fontSize: 12, fontWeight: 700, letterSpacing: 0.15, uppercase: true, italic: true, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.9 },
    bgColor: '#111827', textColor: '#facc15', accentColor: '#fef08a',
    bgConfig: { type: 'gradient', colorStart: '#1e3a8a', colorEnd: '#111827', angle: 135 },
    borderType: 'none', category: 'script', row: 6
  },
  {
    id: 'preset-zappon',
    presetName: 'Zappon',
    arabicPresetName: 'شعار Zappon الكاليغرافي المنسق',
    title: 'Zappon',
    arabicTitle: 'زابون للموسيقى والصوتيات',
    mainText: 'Zappon',
    subtitleText: 'M U S I C',
    mainFontId: 'windsong',
    mainStyle: { text: 'Zappon', fontSize: 110, fontWeight: 500, letterSpacing: 0.05, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'M U S I C', fontSize: 11, fontWeight: 800, letterSpacing: 0.4, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.9 },
    bgColor: '#09090b', textColor: '#fafafa', accentColor: '#e4e4e7',
    bgConfig: { type: 'solid', colorStart: '#09090b', colorEnd: '#1f2937', angle: 180 },
    borderType: 'none', category: 'script', row: 6
  },
  {
    id: 'preset-centaur',
    presetName: 'Centaur',
    arabicPresetName: 'شعار Centaur الكلاسيكي بذيل روماني',
    title: 'Centaur',
    arabicTitle: 'سنتور الرياضية والأكاديمية',
    mainText: 'Centaur',
    subtitleText: '► PARTNER ◄',
    mainFontId: 'playfair-display',
    mainStyle: { text: 'Centaur', fontSize: 65, fontWeight: 800, letterSpacing: 0.06, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: '► PARTNER ◄', fontSize: 11, fontWeight: 600, letterSpacing: 0.25, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.8 },
    bgColor: '#1c1917', textColor: '#fafafa', accentColor: '#d6d3d1',
    bgConfig: { type: 'solid', colorStart: '#1c1917', colorEnd: '#000000', angle: 180 },
    borderType: 'double', category: 'serif', row: 6
  },
  {
    id: 'preset-23',
    presetName: '23',
    arabicPresetName: 'شعار 23 الأسطوري الممتلئ',
    title: '23',
    arabicTitle: 'رقم الأساطير الثالث والعشرون',
    mainText: '23',
    subtitleText: 'Legend',
    mainFontId: 'archivo-black',
    mainStyle: { text: '23', fontSize: 125, fontWeight: 955, letterSpacing: -0.05, lineHeight: 0.9, uppercase: true, italic: true, textShadow: 'none' },
    subtitleFontId: 'great-vibes',
    subtitleStyle: { text: 'Legend', fontSize: 28, fontWeight: 500, letterSpacing: 0.05, uppercase: false, italic: false, fontFamily: '"Great Vibes", cursive', visible: true, opacity: 0.95 },
    bgColor: '#171717', textColor: '#ffffff', accentColor: '#facc15',
    bgConfig: { type: 'solid', colorStart: '#171717', colorEnd: '#000000', angle: 180 },
    borderType: 'none', category: 'display', row: 6
  },

  // --- ROW 7 ---
  {
    id: 'preset-maximum',
    presetName: 'MAXIMUM',
    arabicPresetName: 'شعار MAXIMUM الصناعي المضغوط الهيكل',
    title: 'MAXIMUM',
    arabicTitle: 'ماكسيمم للمصانع والورش',
    mainText: 'MAXIMUM',
    subtitleText: '• FACTORY •',
    mainFontId: 'anton',
    mainStyle: { text: 'MAXIMUM', fontSize: 88, fontWeight: 900, letterSpacing: 0.05, lineHeight: 0.95, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'space-mono',
    subtitleStyle: { text: '• FACTORY •', fontSize: 11, fontWeight: 650, letterSpacing: 0.3, uppercase: true, italic: false, fontFamily: '"Space Mono", monospace', visible: true, opacity: 0.8 },
    bgColor: '#09090b', textColor: '#ffffff', accentColor: '#dc2626',
    bgConfig: { type: 'solid', colorStart: '#09090b', colorEnd: '#1c1917', angle: 180 },
    borderType: 'accent-line', category: 'display', row: 7
  },
  {
    id: 'preset-jordan',
    presetName: 'Jordan Knight',
    arabicPresetName: 'شعار Jordan Knight اليدوي الفاخر',
    title: 'Jordan Knight',
    arabicTitle: 'جوردان نايت للمحاماة',
    mainText: 'Jordan Knight',
    subtitleText: 'LAW AGENCY',
    mainFontId: 'great-vibes',
    mainStyle: { text: 'Jordan Knight', fontSize: 88, fontWeight: 500, letterSpacing: 0.02, lineHeight: 1.2, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'plus-jakarta-sans',
    subtitleStyle: { text: 'LAW AGENCY', fontSize: 11, fontWeight: 600, letterSpacing: 0.35, uppercase: true, italic: false, fontFamily: '"Plus Jakarta Sans", sans-serif', visible: true, opacity: 0.75 },
    bgColor: '#18181b', textColor: '#fefefe', accentColor: '#cbd5e1',
    bgConfig: { type: 'solid', colorStart: '#18181b', colorEnd: '#09090b', angle: 180 },
    borderType: 'none', category: 'script', row: 7
  },
  {
    id: 'preset-limousines',
    presetName: 'Limousines',
    arabicPresetName: 'شعار Limousines للأعمال والنقل الفاره',
    title: 'Limousines',
    arabicTitle: 'ليموزين الخدمات الخاصة والأعمال',
    mainText: 'Limousines',
    subtitleText: 'SPECIAL SERVICE',
    mainFontId: 'cormorant-garamond',
    mainStyle: { text: 'Limousines', fontSize: 75, fontWeight: 500, letterSpacing: 0.06, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'SPECIAL SERVICE', fontSize: 10, fontWeight: 700, letterSpacing: 0.45, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.75 },
    bgColor: '#171717', textColor: '#fbf5eb', accentColor: '#dfc090',
    bgConfig: { type: 'gradient', colorStart: '#1c1917', colorEnd: '#0a0a0a', angle: 155 },
    borderType: 'none', category: 'serif', row: 7
  },
  {
    id: 'preset-travel',
    presetName: 'Travel',
    arabicPresetName: 'شعار Travel السياحي المبهج الفرشاه',
    title: 'Travel',
    arabicTitle: 'ترافيل للسياحة بروش الساحر',
    mainText: 'Travel',
    subtitleText: '— ONLINE —',
    mainFontId: 'pacifico',
    mainStyle: { text: 'Travel', fontSize: 76, fontWeight: 400, letterSpacing: 0, lineHeight: 1.2, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'space-grotesk',
    subtitleStyle: { text: '— ONLINE —', fontSize: 11, fontWeight: 800, letterSpacing: 0.3, uppercase: true, italic: false, fontFamily: '"Space Grotesk", sans-serif', visible: true, opacity: 0.85 },
    bgColor: '#0284c7', textColor: '#ffffff', accentColor: '#bae6fd',
    bgConfig: { type: 'gradient', colorStart: '#0369a1', colorEnd: '#0c4a6e', angle: 135 },
    borderType: 'none', category: 'script', row: 7
  },

  // --- ROW 8 ---
  {
    id: 'preset-diamonds',
    presetName: 'Diamonds',
    arabicPresetName: 'شعار Diamonds للذهب والمجوهرات الرقيقة',
    title: 'Diamonds',
    arabicTitle: 'ألماس الفخامة والاستوديو اليدوي',
    mainText: 'Diamonds',
    subtitleText: 'E X C L U S I V E',
    mainFontId: 'windsong',
    mainStyle: { text: 'Diamonds', fontSize: 110, fontWeight: 500, letterSpacing: 0.02, lineHeight: 1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'cinzel',
    subtitleStyle: { text: 'E X C L U S I V E', fontSize: 11, fontWeight: 800, letterSpacing: 0.5, uppercase: true, italic: false, fontFamily: '"Cinzel", serif', visible: true, opacity: 0.9 },
    bgColor: '#111111', textColor: '#ffffff', accentColor: '#c5a880',
    bgConfig: { type: 'radial', colorStart: '#262626', colorEnd: '#0a0a0a', angle: 180 },
    borderType: 'double', category: 'script', row: 8
  },
  {
    id: 'preset-chocos',
    presetName: 'CHOCOS',
    arabicPresetName: 'شعار CHOCOS للشيكولاتة والحلوى الجريء',
    title: 'CHOCOS',
    arabicTitle: 'شوكوس لمنتجات الكاكاو',
    mainText: 'CHOCOS',
    subtitleText: 'supermaket',
    mainFontId: 'anton',
    mainStyle: { text: 'CHOCOS', fontSize: 80, fontWeight: 900, letterSpacing: 0.02, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'great-vibes',
    subtitleStyle: { text: 'supermaket', fontSize: 26, fontWeight: 400, letterSpacing: 0.05, uppercase: false, italic: false, fontFamily: '"Great Vibes", cursive', visible: true, opacity: 0.9 },
    bgColor: '#451a03', textColor: '#fef3c7', accentColor: '#f59e0b',
    bgConfig: { type: 'gradient', colorStart: '#451a03', colorEnd: '#290f01', angle: 135 },
    borderType: 'none', category: 'display', row: 8
  },
  {
    id: 'preset-charmed',
    presetName: 'Charmed',
    arabicPresetName: 'شعار Charmed الاستوديو الإبداعي الروماني',
    title: 'Charmed',
    arabicTitle: 'استوديو السحر والجمال الروماني',
    mainText: 'Charmed',
    subtitleText: 'CREATIVE STUDIOS',
    mainFontId: 'cinzel',
    mainStyle: { text: 'Charmed', fontSize: 62, fontWeight: 800, letterSpacing: 0.05, lineHeight: 1.1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'CREATIVE STUDIOS', fontSize: 10, fontWeight: 600, letterSpacing: 0.4, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.8 },
    bgColor: '#171717', textColor: '#ffffff', accentColor: '#cbd5e1',
    bgConfig: { type: 'solid', colorStart: '#171717', colorEnd: '#09090b', angle: 180 },
    borderType: 'accent-line', category: 'serif', row: 8
  },
  {
    id: 'preset-oscar',
    presetName: '76 OSCAR',
    arabicPresetName: 'شعار 76 OSCAR الرياضي الأنيق',
    title: '76 OSCAR',
    arabicTitle: '76 أوسكار للجوائز',
    mainText: '76 OSCAR',
    subtitleText: '════► Awards',
    mainFontId: 'montserrat',
    mainStyle: { text: '76 OSCAR', fontSize: 66, fontWeight: 800, letterSpacing: 0.03, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'space-mono',
    subtitleStyle: { text: '════► Awards', fontSize: 13, fontWeight: 700, letterSpacing: 0.2, uppercase: false, italic: true, fontFamily: '"Space Mono", monospace', visible: true, opacity: 0.9 },
    bgColor: '#18181b', textColor: '#ffffff', accentColor: '#fbbf24',
    bgConfig: { type: 'gradient', colorStart: '#171717', colorEnd: '#0a0a0a', angle: 180 },
    borderType: 'none', category: 'display', row: 8
  },

  // --- ROW 9 ---
  {
    id: 'preset-volcano',
    presetName: 'VOLCANO',
    arabicPresetName: 'شعار VOLCANO الجريء المستدام',
    title: 'VOLCANO',
    arabicTitle: 'فولكانو صالات ومعارض الفن',
    mainText: 'VOLCANO',
    subtitleText: 'public gallery',
    mainFontId: 'archivo-black',
    mainStyle: { text: 'VOLCANO', fontSize: 72, fontWeight: 950, letterSpacing: 0.03, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'great-vibes',
    subtitleStyle: { text: 'public gallery', fontSize: 24, fontWeight: 400, letterSpacing: 0.05, uppercase: false, italic: false, fontFamily: '"Great Vibes", cursive', visible: true, opacity: 0.9 },
    bgColor: '#121212', textColor: '#ffffff', accentColor: '#ea580c',
    bgConfig: { type: 'solid', colorStart: '#121212', colorEnd: '#262626', angle: 180 },
    borderType: 'none', category: 'display', row: 9
  },
  {
    id: 'preset-youth',
    presetName: 'youth',
    arabicPresetName: 'شعار youth الرياضي والشبابي',
    title: 'youth',
    arabicTitle: 'شباب ونشاط للوكالات الإعلانية',
    mainText: 'youth',
    subtitleText: '◄ AGENCY ►',
    mainFontId: 'pacifico',
    mainStyle: { text: 'youth', fontSize: 78, fontWeight: 500, letterSpacing: 0, lineHeight: 1.2, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'space-grotesk',
    subtitleStyle: { text: '◄ AGENCY ►', fontSize: 12, fontWeight: 800, letterSpacing: 0.25, uppercase: true, italic: false, fontFamily: '"Space Grotesk", sans-serif', visible: true, opacity: 0.9 },
    bgColor: '#111827', textColor: '#ffffff', accentColor: '#f472b6',
    bgConfig: { type: 'radial', colorStart: '#1f2937', colorEnd: '#111827', angle: 180 },
    borderType: 'rounded', category: 'script', row: 9
  },
  {
    id: 'preset-stainy',
    presetName: 'Stainy',
    arabicPresetName: 'شعار Stainy الكاليغرافي السريع',
    title: 'Stainy',
    arabicTitle: 'ستايني للمجلات والموضة',
    mainText: 'Stainy',
    subtitleText: 'M A G A Z I N E',
    mainFontId: 'birthstone-bounce',
    mainStyle: { text: 'Stainy', fontSize: 110, fontWeight: 700, letterSpacing: 0.04, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'space-mono',
    subtitleStyle: { text: 'M A G A Z I N E', fontSize: 11, fontWeight: 600, letterSpacing: 0.3, uppercase: true, italic: false, fontFamily: '"Space Mono", monospace', visible: true, opacity: 0.8 },
    bgColor: '#1e1b4b', textColor: '#fae8ff', accentColor: '#cbd5e1',
    bgConfig: { type: 'gradient', colorStart: '#1e1b4b', colorEnd: '#09090b', angle: 135 },
    borderType: 'none', category: 'script', row: 9
  },
  {
    id: 'preset-primer',
    presetName: 'Primer Movie',
    arabicPresetName: 'شعار Primer Movie الروماني الكلاسيكي المنسق',
    title: 'Primer Movie',
    arabicTitle: 'برايمر موفي لخدمات وتذاكر السينما',
    mainText: 'Primer Movie',
    subtitleText: '── YOUR TICKET SUPPORT ──',
    mainFontId: 'playfair-display',
    mainStyle: { text: 'Primer Movie', fontSize: 60, fontWeight: 800, letterSpacing: 0.02, lineHeight: 1.1, uppercase: false, italic: true, textShadow: 'none' },
    subtitleFontId: 'jetbrains-mono',
    subtitleStyle: { text: '── YOUR TICKET SUPPORT ──', fontSize: 10, fontWeight: 550, letterSpacing: 0.25, uppercase: true, italic: false, fontFamily: '"JetBrains Mono", monospace', visible: true, opacity: 0.75 },
    bgColor: '#111', textColor: '#ffffff', accentColor: '#cbd5e1',
    bgConfig: { type: 'solid', colorStart: '#111', colorEnd: '#292524', angle: 180 },
    borderType: 'none', category: 'serif', row: 9
  },

  // --- ROW 10 ---
  {
    id: 'preset-scriptonen',
    presetName: 'Scriptonen',
    arabicPresetName: 'شعار Scriptonen السميك الفني',
    title: 'Scriptonen',
    arabicTitle: 'سكريبتونن لوكالات الإعلان والتصميم',
    mainText: 'Scriptonen',
    subtitleText: 'CREATIVE █ AGENCY LEADS',
    mainFontId: 'windsong',
    mainStyle: { text: 'Scriptonen', fontSize: 105, fontWeight: 450, letterSpacing: 0.05, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'CREATIVE █ AGENCY LEADS', fontSize: 11, fontWeight: 750, letterSpacing: 0.2, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.9 },
    bgColor: '#111111', textColor: '#ffffff', accentColor: '#fbbf24',
    bgConfig: { type: 'solid', colorStart: '#111111', colorEnd: '#1e1e1e', angle: 180 },
    borderType: 'thin', category: 'script', row: 10
  },
  {
    id: 'preset-olympic',
    presetName: 'Olympic',
    arabicPresetName: 'شعار Olympic الإبداعي المزدوج الإطار',
    title: 'Olympic',
    arabicTitle: 'أولمبيك الرياضية',
    mainText: 'Olympic',
    subtitleText: 'C O .',
    mainFontId: 'unbounded',
    mainStyle: { text: 'Olympic', fontSize: 62, fontWeight: 800, letterSpacing: 0.04, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'C O .', fontSize: 13, fontWeight: 800, letterSpacing: 0.2, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.9 },
    bgColor: '#161d1d', textColor: '#ffffff', accentColor: '#10b981',
    bgConfig: { type: 'radial', colorStart: '#111827', colorEnd: '#030712', angle: 180 },
    borderType: 'double', category: 'display', row: 10
  },
  {
    id: 'preset-delicious',
    presetName: 'DELICIOUS',
    arabicPresetName: 'شعار DELICIOUS الراقي للمطاعم الفاخرة',
    title: 'DELICIOUS',
    arabicTitle: 'ديليشوس كافيه بريميوم',
    mainText: 'DELICIOUS',
    subtitleText: 'premium cafe',
    mainFontId: 'cormorant-garamond',
    mainStyle: { text: 'DELICIOUS', fontSize: 75, fontWeight: 600, letterSpacing: 0.08, lineHeight: 1.1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'great-vibes',
    subtitleStyle: { text: 'premium cafe', fontSize: 24, fontWeight: 400, letterSpacing: 0.04, uppercase: false, italic: false, fontFamily: '"Great Vibes", cursive', visible: true, opacity: 0.9 },
    bgColor: '#1c1917', textColor: '#fefefe', accentColor: '#c5a880',
    bgConfig: { type: 'solid', colorStart: '#1c1917', colorEnd: '#0f172a', angle: 180 },
    borderType: 'rounded', category: 'serif', row: 10
  },
  {
    id: 'preset-imperials',
    presetName: 'Imperials',
    arabicPresetName: 'شعار Imperials الإمبراطوري الروماني الفخم',
    title: 'Imperials',
    arabicTitle: 'إمبيريالز للأزياء الفخمة الكلاسيك',
    mainText: 'Imperials',
    subtitleText: 'T H E   O R I G I N A L S',
    mainFontId: 'cinzel',
    mainStyle: { text: 'Imperials', fontSize: 62, fontWeight: 800, letterSpacing: 0.05, lineHeight: 1.1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'T H E   O R I G I N A L S', fontSize: 10, fontWeight: 700, letterSpacing: 0.45, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.9 },
    bgColor: '#111', textColor: '#fdfdfd', accentColor: '#c5a880',
    bgConfig: { type: 'gradient', colorStart: '#171717', colorEnd: '#022c22', angle: 135 },
    borderType: 'none', category: 'serif', row: 10
  },

  // --- ROW 11 ---
  {
    id: 'preset-southern',
    presetName: 'Southern',
    arabicPresetName: 'شعار Southern التراثي الجذاب للأطعمة',
    title: 'Southern',
    arabicTitle: 'سوذرن فود مطبخ زمان المتنقل',
    mainText: 'Southern',
    subtitleText: 'your original food',
    mainFontId: 'great-vibes',
    mainStyle: { text: 'Southern', fontSize: 94, fontWeight: 500, letterSpacing: 0.02, lineHeight: 1.2, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'plus-jakarta-sans',
    subtitleStyle: { text: 'your original food', fontSize: 12, fontWeight: 650, letterSpacing: 0.15, uppercase: false, italic: true, fontFamily: '"Plus Jakarta Sans", sans-serif', visible: true, opacity: 0.8 },
    bgColor: '#292524', textColor: '#fef3c7', accentColor: '#fddf80',
    bgConfig: { type: 'solid', colorStart: '#292524', colorEnd: '#1c1917', angle: 180 },
    borderType: 'accent-line', category: 'script', row: 11
  },
  {
    id: 'preset-pacific',
    presetName: 'capital Pacific',
    arabicPresetName: 'شعار capital Pacific التجاري الواعد الكاليغرافي',
    title: 'capital Pacific',
    arabicTitle: 'كابيتال باسيفيك للاستثمارات الرائد',
    mainText: 'capital Pacific',
    subtitleText: 'ESTABLISHED 2026',
    mainFontId: 'windsong',
    mainStyle: { text: 'capital Pacific', fontSize: 105, fontWeight: 500, letterSpacing: 0.04, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'ESTABLISHED 2026', fontSize: 11, fontWeight: 700, letterSpacing: 0.3, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.85 },
    bgColor: '#0f172a', textColor: '#fafafa', accentColor: '#38bdf8',
    bgConfig: { type: 'gradient', colorStart: '#0f172a', colorEnd: '#020617', angle: 135 },
    borderType: 'none', category: 'script', row: 11
  },
  {
    id: 'preset-kenzo',
    presetName: 'KENZO',
    arabicPresetName: 'شعار KENZO الصارم الهيكلي المونومينيمال',
    title: 'KENZO',
    arabicTitle: 'كينزو شيرت للأزياء التقنية والرياضية',
    mainText: 'KENZO',
    subtitleText: 'japan passion',
    mainFontId: 'space-mono',
    mainStyle: { text: 'KENZO', fontSize: 75, fontWeight: 900, letterSpacing: 0.15, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'jetbrains-mono',
    subtitleStyle: { text: 'japan passion', fontSize: 11, fontWeight: 550, letterSpacing: 0.25, uppercase: true, italic: false, fontFamily: '"JetBrains Mono", monospace', visible: true, opacity: 0.8 },
    bgColor: '#171717', textColor: '#ffffff', accentColor: '#d6d3d1',
    bgConfig: { type: 'solid', colorStart: '#171717', colorEnd: '#292524', angle: 180 },
    borderType: 'thick', category: 'display', row: 11
  },
  {
    id: 'preset-dolores',
    presetName: 'DOLORES',
    arabicPresetName: 'شعار DOLORES رقيق الهوية للعطور',
    title: 'DOLORES',
    arabicTitle: 'دولوريس عطور الموضة والنقاء',
    mainText: 'DOLORES',
    subtitleText: 'Parfume',
    mainFontId: 'bodoni-moda',
    mainStyle: { text: 'DOLORES', fontSize: 64, fontWeight: 905, letterSpacing: 0.1, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'great-vibes',
    subtitleStyle: { text: 'Parfume', fontSize: 28, fontWeight: 400, letterSpacing: 0.05, uppercase: false, italic: false, fontFamily: '"Great Vibes", cursive', visible: true, opacity: 0.9 },
    bgColor: '#161313', textColor: '#ffffff', accentColor: '#cbd5e1',
    bgConfig: { type: 'solid', colorStart: '#161313', colorEnd: '#09090b', angle: 180 },
    borderType: 'none', category: 'serif', row: 11
  },

  // --- ROW 12 ---
  {
    id: 'preset-fabric',
    presetName: 'FABRIC',
    arabicPresetName: 'شعار FABRIC التقني الهندسي',
    title: 'FABRIC',
    arabicTitle: 'فابريك للمنسوجات والألبسة الفنية',
    mainText: 'FABRIC',
    subtitleText: 'INDUSTRIES',
    mainFontId: 'space-grotesk',
    mainStyle: { text: 'FABRIC', fontSize: 75, fontWeight: 700, letterSpacing: 0.08, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'INDUSTRIES', fontSize: 11, fontWeight: 600, letterSpacing: 0.35, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.8 },
    bgColor: '#111827', textColor: '#ffffff', accentColor: '#cbd5e1',
    bgConfig: { type: 'gradient', colorStart: '#111827', colorEnd: '#030712', angle: 180 },
    borderType: 'thin', category: 'sans', row: 12
  },
  {
    id: 'preset-master',
    presetName: 'Master',
    arabicPresetName: 'شعار Master الرياضي الطائر الراقي',
    title: 'Master',
    arabicTitle: 'ماستر للأزياء والملابس بروش',
    mainText: 'Master',
    subtitleText: 'A P P A R E L',
    mainFontId: 'windsong',
    mainStyle: { text: 'Master', fontSize: 115, fontWeight: 500, letterSpacing: 0.02, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'A P P A R E L', fontSize: 11, fontWeight: 700, letterSpacing: 0.4, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.85 },
    bgColor: '#0f172a', textColor: '#ffffff', accentColor: '#38bdf8',
    bgConfig: { type: 'solid', colorStart: '#0f172a', colorEnd: '#1e293b', angle: 180 },
    borderType: 'none', category: 'script', row: 12
  },
  {
    id: 'preset-clothing25',
    presetName: '25',
    arabicPresetName: 'شعار 25 الأيقوني ذو الخط المائل الحركي',
    title: '25',
    arabicTitle: 'خمس وعشرون ديزاين للملابس',
    mainText: '25',
    subtitleText: 'clothing',
    mainFontId: 'archivo-black',
    mainStyle: { text: '25', fontSize: 110, fontWeight: 900, letterSpacing: -0.04, lineHeight: 1, uppercase: true, italic: true, textShadow: 'none' },
    subtitleFontId: 'great-vibes',
    subtitleStyle: { text: 'clothing', fontSize: 26, fontWeight: 400, letterSpacing: 0.05, uppercase: false, italic: false, fontFamily: '"Great Vibes", cursive', visible: true, opacity: 0.9 },
    bgColor: '#171717', textColor: '#ffffff', accentColor: '#fbbf24',
    bgConfig: { type: 'solid', colorStart: '#171717', colorEnd: '#000', angle: 90 },
    borderType: 'none', category: 'display', row: 12
  },
  {
    id: 'preset-hitachi',
    presetName: 'Hitachi',
    arabicPresetName: 'شعار Hitachi الناعم النظيف للأعمال',
    title: 'Hitachi',
    arabicTitle: 'هيتاتشي نشر وتدوين أعمال هندسية',
    mainText: 'Hitachi',
    subtitleText: 'PUBLISHER',
    mainFontId: 'sacramento',
    mainStyle: { text: 'Hitachi', fontSize: 95, fontWeight: 450, letterSpacing: 0.05, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'PUBLISHER', fontSize: 11, fontWeight: 650, letterSpacing: 0.35, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.8 },
    bgColor: '#111', textColor: '#fafafa', accentColor: '#cbd5e1',
    bgConfig: { type: 'solid', colorStart: '#111', colorEnd: '#222', angle: 180 },
    borderType: 'none', category: 'script', row: 12
  },
  {
    id: 'preset-creative-agency',
    presetName: 'Creative AGENCY',
    arabicPresetName: 'شعار Creative الرفيع النظيف الجذاب',
    title: 'Creative',
    arabicTitle: 'الوكالة الإبداعية الحديثة',
    mainText: 'Creative',
    subtitleText: 'A G E N C Y',
    mainFontId: 'plus-jakarta-sans',
    mainStyle: { text: 'Creative', fontSize: 75, fontWeight: 700, letterSpacing: 0.03, lineHeight: 1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'A G E N C Y', fontSize: 11, fontWeight: 550, letterSpacing: 0.45, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.8 },
    bgColor: '#1c1917', textColor: '#fefefe', accentColor: '#cbd5e1',
    bgConfig: { type: 'gradient', colorStart: '#1c1917', colorEnd: '#0c0a09', angle: 135 },
    borderType: 'accent-line', category: 'serif', row: 12
  },

  // --- ROW 13 ---
  {
    id: 'preset-butterking',
    presetName: 'Butter King',
    arabicPresetName: 'شعار Butter King للمأكولات المبهجة والمنتجات',
    title: 'Butter King',
    arabicTitle: 'ملك الزبدة كافيه ريترو',
    mainText: 'Butter King',
    subtitleText: 'ATLANTA CITY',
    mainFontId: 'birthstone-bounce',
    mainStyle: { text: 'Butter King', fontSize: 94, fontWeight: 400, letterSpacing: 0, lineHeight: 1.2, uppercase: false, italic: false, textShadow: 'subtle' },
    subtitleFontId: 'fraunces',
    subtitleStyle: { text: 'ATLANTA CITY', fontSize: 13, fontWeight: 600, letterSpacing: 0.25, uppercase: true, italic: true, fontFamily: '"Fraunces", serif', visible: true, opacity: 0.85 },
    bgColor: '#7c2d12', textColor: '#fef3c7', accentColor: '#f59e0b',
    bgConfig: { type: 'gradient', colorStart: '#431407', colorEnd: '#1c0500', angle: 155 },
    borderType: 'rounded', category: 'script', row: 13
  },
  {
    id: 'preset-devender',
    presetName: '57 DEVENDER',
    arabicPresetName: 'شعار 57 DEVENDER الرقمي المبرمج',
    title: '57 DEVENDER',
    arabicTitle: '57 ديفندر للمطورين ومواقع الويب',
    mainText: '57 DEVENDER',
    subtitleText: 'WEB AND DESIGNER',
    mainFontId: 'fira-code',
    mainStyle: { text: '57 DEVENDER', fontSize: 44, fontWeight: 650, letterSpacing: 0.05, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'jetbrains-mono',
    subtitleStyle: { text: 'WEB AND DESIGNER', fontSize: 10, fontWeight: 600, letterSpacing: 0.3, uppercase: true, italic: false, fontFamily: '"JetBrains Mono", monospace', visible: true, opacity: 0.75 },
    bgColor: '#0c0a09', textColor: '#ffffff', accentColor: '#34d399',
    bgConfig: { type: 'grid', colorStart: '#0c0a09', colorEnd: '#172554', angle: 180 },
    borderType: 'thin', category: 'sans', row: 13
  },
  {
    id: 'preset-raze',
    presetName: 'RAZE',
    arabicPresetName: 'شعار RAZE الرياضي الجسيم المضغوط',
    title: 'RAZE',
    arabicTitle: 'ريز الرياضية بولد سبورت',
    mainText: 'RAZE',
    subtitleText: 'OREGON',
    mainFontId: 'anton',
    mainStyle: { text: 'RAZE', fontSize: 110, fontWeight: 900, letterSpacing: -0.01, lineHeight: 0.9, uppercase: true, italic: true, textShadow: 'retro' },
    subtitleFontId: 'space-grotesk',
    subtitleStyle: { text: 'OREGON', fontSize: 13, fontWeight: 800, letterSpacing: 0.25, uppercase: true, italic: false, fontFamily: '"Space Grotesk", sans-serif', visible: true, opacity: 0.95 },
    bgColor: '#1e3a8a', textColor: '#facc15', accentColor: '#f87171',
    bgConfig: { type: 'gradient', colorStart: '#1e3a8a', colorEnd: '#172554', angle: 180 },
    borderType: 'none', category: 'display', row: 13
  },
  {
    id: 'preset-city',
    presetName: 'City',
    arabicPresetName: 'شعار City السريع المميز المتفرد',
    title: 'City',
    arabicTitle: 'سيتي كورب للمستحضر والمشاريع النظيفة',
    mainText: 'City',
    subtitleText: 'CORP',
    mainFontId: 'windsong',
    mainStyle: { text: 'City', fontSize: 115, fontWeight: 500, letterSpacing: 0.02, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'jetbrains-mono',
    subtitleStyle: { text: 'CORP', fontSize: 11, fontWeight: 700, letterSpacing: 0.3, uppercase: true, italic: false, fontFamily: '"JetBrains Mono", monospace', visible: true, opacity: 0.8 },
    bgColor: '#09090b', textColor: '#ffffff', accentColor: '#cbd5e1',
    bgConfig: { type: 'solid', colorStart: '#09090b', colorEnd: '#1f2937', angle: 180 },
    borderType: 'rounded', category: 'script', row: 13
  },
  {
    id: 'preset-75',
    presetName: '75',
    arabicPresetName: 'شعار 75 الأيقوني ذو التفاصيل المستقبلية الأحدث',
    title: '75',
    arabicTitle: 'ألعاب 75 المستقبلية التكتيكية',
    mainText: '75',
    subtitleText: 'GAMES',
    mainFontId: 'unbounded',
    mainStyle: { text: '75', fontSize: 94, fontWeight: 850, letterSpacing: 0.01, lineHeight: 0.95, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'GAMES', fontSize: 12, fontWeight: 800, letterSpacing: 0.35, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.9 },
    bgColor: '#121212', textColor: '#ffffff', accentColor: '#a855f7',
    bgConfig: { type: 'gradient', colorStart: '#2e1065', colorEnd: '#121212', angle: 180 },
    borderType: 'none', category: 'display', row: 13
  },

  // --- ROW 14 ---
  {
    id: 'preset-angila',
    presetName: 'Angila',
    arabicPresetName: 'شعار Angila الفخم اليدوي للمصممين',
    title: 'Angila',
    arabicTitle: 'أنجيلا لمصممي الديكور والموضة',
    mainText: 'Angila',
    subtitleText: 'designer',
    mainFontId: 'great-vibes',
    mainStyle: { text: 'Angila', fontSize: 92, fontWeight: 400, letterSpacing: 0.02, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'space-mono',
    subtitleStyle: { text: 'designer', fontSize: 12, fontWeight: 600, letterSpacing: 0.2, uppercase: false, italic: true, fontFamily: '"Space Mono", monospace', visible: true, opacity: 0.8 },
    bgColor: '#181313', textColor: '#ffffff', accentColor: '#fda4af',
    bgConfig: { type: 'solid', colorStart: '#181313', colorEnd: '#090505', angle: 180 },
    borderType: 'rounded', category: 'script', row: 14
  },
  {
    id: 'preset-cash',
    presetName: 'CASH',
    arabicPresetName: 'شعار CASH الصلب العريض للتسلية والترفيه',
    title: 'CASH',
    arabicTitle: 'كاش إنترتينمنت للمسابات',
    mainText: 'CASH',
    subtitleText: 'ENTERTAINMENT',
    mainFontId: 'oswald',
    mainStyle: { text: 'CASH', fontSize: 80, fontWeight: 700, letterSpacing: 0.05, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'ENTERTAINMENT', fontSize: 11, fontWeight: 700, letterSpacing: 0.3, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.8 },
    bgColor: '#1c1917', textColor: '#ffffff', accentColor: '#ea580c',
    bgConfig: { type: 'solid', colorStart: '#1c1917', colorEnd: '#0c0a09', angle: 180 },
    borderType: 'none', category: 'display', row: 14
  },
  {
    id: 'preset-top5',
    presetName: 'TOP 5',
    arabicPresetName: 'شعار TOP 5 الفخم العريض المتكامل',
    title: 'TOP 5',
    arabicTitle: 'توب فايف للتقييم والتصنيفات',
    mainText: 'TOP 5',
    subtitleText: 'CORP',
    mainFontId: 'unbounded',
    mainStyle: { text: 'TOP 5', fontSize: 55, fontWeight: 850, letterSpacing: 0.02, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'jetbrains-mono',
    subtitleStyle: { text: 'CORP', fontSize: 12, fontWeight: 650, letterSpacing: 0.3, uppercase: true, italic: false, fontFamily: '"JetBrains Mono", monospace', visible: true, opacity: 0.95 },
    bgColor: '#111', textColor: '#ffffff', accentColor: '#ffffff',
    bgConfig: { type: 'solid', colorStart: '#111', colorEnd: '#222', angle: 180 },
    borderType: 'none', category: 'display', row: 14
  },
  {
    id: 'preset-luck',
    presetName: 'LUCK',
    arabicPresetName: 'شعار LUCK العسكري الأنيق للمصورين الفوتوغرافيين',
    title: 'LUCK',
    arabicTitle: 'لوك لتسجيل اللقطات الرقيقة والراقية',
    mainText: 'LUCK',
    subtitleText: 'PHOTOGRAPHER',
    mainFontId: 'inter',
    mainStyle: { text: 'LUCK', fontSize: 75, fontWeight: 300, letterSpacing: 0.12, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'jetbrains-mono',
    subtitleStyle: { text: 'PHOTOGRAPHER', fontSize: 10, fontWeight: 400, letterSpacing: 0.45, uppercase: true, italic: false, fontFamily: '"JetBrains Mono", monospace', visible: true, opacity: 0.75 },
    bgColor: '#09090b', textColor: '#ffffff', accentColor: '#e4e4e7',
    bgConfig: { type: 'solid', colorStart: '#09090b', colorEnd: '#1e1b4b', angle: 180 },
    borderType: 'accent-line', category: 'sans', row: 14
  },
  {
    id: 'preset-april',
    presetName: 'April',
    arabicPresetName: 'شعار April الأنثوي الساحر المنسق رقيق',
    title: 'April',
    arabicTitle: 'أبريل لعلامات مستحضرات الجمال الراقية',
    mainText: 'April',
    subtitleText: 'C O R P .',
    mainFontId: 'allura',
    mainStyle: { text: 'April', fontSize: 105, fontWeight: 400, letterSpacing: 0.05, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'space-mono',
    subtitleStyle: { text: 'C O R P .', fontSize: 11, fontWeight: 600, letterSpacing: 0.45, uppercase: true, italic: false, fontFamily: '"Space Mono", monospace', visible: true, opacity: 0.8 },
    bgColor: '#1f1311', textColor: '#ffe4e6', accentColor: '#f43f5e',
    bgConfig: { type: 'gradient', colorStart: '#311212', colorEnd: '#0c0202', angle: 135 },
    borderType: 'none', category: 'script', row: 14
  },

  // --- ROW 15 ---
  {
    id: 'preset-looper',
    presetName: 'Looper',
    arabicPresetName: 'شعار Looper الهندسي للألبسة التكنولوجية',
    title: 'Looper',
    arabicTitle: 'لوبر لملابس المبرمجين والتقنية السائدة',
    mainText: 'Looper',
    subtitleText: 'apparel',
    mainFontId: 'space-grotesk',
    mainStyle: { text: 'Looper', fontSize: 82, fontWeight: 700, letterSpacing: -0.01, lineHeight: 1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'apparel', fontSize: 12, fontWeight: 650, letterSpacing: 0.2, uppercase: false, italic: true, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.9 },
    bgColor: '#020617', textColor: '#ffffff', accentColor: '#cbd5e1',
    bgConfig: { type: 'solid', colorStart: '#020617', colorEnd: '#0f172a', angle: 180 },
    borderType: 'rounded', category: 'sans', row: 15
  },
  {
    id: 'preset-solution',
    presetName: 'the winner SOLUTION',
    arabicPresetName: 'شعار the winner الفاخر لشهادات التقدير والحلول',
    title: 'the winner SOLUTION',
    arabicTitle: 'الفائز للحلول الريادية المنسق اليدوي والتايب',
    mainText: 'the winner',
    subtitleText: 'S O L U T I O N',
    mainFontId: 'windsong',
    mainStyle: { text: 'the winner', fontSize: 96, fontWeight: 500, letterSpacing: 0.04, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'S O L U T I O N', fontSize: 11, fontWeight: 750, letterSpacing: 0.35, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.9 },
    bgColor: '#1c1917', textColor: '#ffffff', accentColor: '#cbd5e1',
    bgConfig: { type: 'solid', colorStart: '#1c1917', colorEnd: '#000000', angle: 180 },
    borderType: 'none', category: 'script', row: 15
  },
  {
    id: 'preset-bacon',
    presetName: 'Bacon COMPANY',
    arabicPresetName: 'شعار Bacon اليدوي الجريء لغذاء والمشروبات كافيه',
    title: 'Bacon',
    arabicTitle: 'بيكون للأطعمة اللذيذة بروش الكلاسيكي',
    mainText: 'Bacon',
    subtitleText: 'COMPANY',
    mainFontId: 'pacifico',
    mainStyle: { text: 'Bacon', fontSize: 84, fontWeight: 400, letterSpacing: 0, lineHeight: 1.2, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'plus-jakarta-sans',
    subtitleStyle: { text: 'COMPANY', fontSize: 11, fontWeight: 700, letterSpacing: 0.25, uppercase: true, italic: false, fontFamily: '"Plus Jakarta Sans", sans-serif', visible: true, opacity: 0.8 },
    bgColor: '#7c2d12', textColor: '#ffedd5', accentColor: '#ea580c',
    bgConfig: { type: 'gradient', colorStart: '#7c2d12', colorEnd: '#2d0f00', angle: 155 },
    borderType: 'none', category: 'script', row: 15
  },
  {
    id: 'preset-duct',
    presetName: 'Duct',
    arabicPresetName: 'شعار Duct الصناعي الفني للمجلات والتكنولوجيا',
    title: 'Duct',
    arabicTitle: 'داكت للتقنية والمشاريع الرائدة المتطورة',
    mainText: 'Duct',
    subtitleText: 'TECH MAGAZINE',
    mainFontId: 'share-tech-mono',
    mainStyle: { text: 'Duct', fontSize: 75, fontWeight: 650, letterSpacing: 0.05, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'space-mono',
    subtitleStyle: { text: 'TECH MAGAZINE', fontSize: 12, fontWeight: 550, letterSpacing: 0.25, uppercase: true, italic: false, fontFamily: '"Space Mono", monospace', visible: true, opacity: 0.75 },
    bgColor: '#171717', textColor: '#ffffff', accentColor: '#cbd5e1',
    bgConfig: { type: 'solid', colorStart: '#171717', colorEnd: '#292524', angle: 180 },
    borderType: 'accent-line', category: 'display', row: 15
  },
  {
    id: 'preset-joomla',
    presetName: 'Joomla',
    arabicPresetName: 'شعار Joomla التقني المرح للمطورين وصنع البرامج',
    title: 'Joomla',
    arabicTitle: 'جوملا للمبرمجين بلمستك الفرواشة',
    mainText: 'Joomla',
    subtitleText: 'DEVELOPER',
    mainFontId: 'pacifico',
    mainStyle: { text: 'Joomla', fontSize: 78, fontWeight: 400, letterSpacing: 0.02, lineHeight: 1.2, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'DEVELOPER', fontSize: 11, fontWeight: 800, letterSpacing: 0.3, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.95 },
    bgColor: '#0284c7', textColor: '#ffffff', accentColor: '#bae6fd',
    bgConfig: { type: 'gradient', colorStart: '#0284c7', colorEnd: '#075985', angle: 135 },
    borderType: 'none', category: 'script', row: 15
  },

  // --- ROW 16 ---
  {
    id: 'preset-rohan',
    presetName: 'Rohan Sable',
    arabicPresetName: 'شعار Rohan Sable للفيديو والسينما اليدوية',
    title: 'Rohan Sable',
    arabicTitle: 'روهان سابل لتسجيل المقاطع البصرية البهيئة',
    mainText: 'Rohan Sable',
    subtitleText: 'VIDEOGRAPHY',
    mainFontId: 'sacramento',
    mainStyle: { text: 'Rohan Sable', fontSize: 94, fontWeight: 405, letterSpacing: 0.05, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'VIDEOGRAPHY', fontSize: 11, fontWeight: 700, letterSpacing: 0.35, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.8 },
    bgColor: '#121212', textColor: '#ffffff', accentColor: '#cbd5e1',
    bgConfig: { type: 'solid', colorStart: '#121212', colorEnd: '#1e1e1e', angle: 180 },
    borderType: 'none', category: 'script', row: 16
  },
  {
    id: 'preset-human',
    presetName: 'Human',
    arabicPresetName: 'شعار Human الهندسي الفاخر الريترو',
    title: 'Human',
    arabicTitle: 'إنساني للمشاريع والتنمية والجرارات العتيقة',
    mainText: 'Human',
    subtitleText: 'tractors',
    mainFontId: 'birthstone-bounce',
    mainStyle: { text: 'Human', fontSize: 110, fontWeight: 600, letterSpacing: 0.02, lineHeight: 1.1, uppercase: false, italic: true, textShadow: 'none' },
    subtitleFontId: 'space-mono',
    subtitleStyle: { text: 'tractors', fontSize: 12, fontWeight: 600, letterSpacing: 0.2, uppercase: false, italic: true, fontFamily: '"Space Mono", monospace', visible: true, opacity: 0.85 },
    bgColor: '#3b2314', textColor: '#fef3c7', accentColor: '#d97706',
    bgConfig: { type: 'radial', colorStart: '#451a03', colorEnd: '#1c0a02', angle: 185 },
    borderType: 'none', category: 'script', row: 16
  },
  {
    id: 'preset-captain',
    presetName: 'CAPTAIN',
    arabicPresetName: 'شعار CAPTAIN التسويقي الممتد النظيف',
    title: 'CAPTAIN',
    arabicTitle: 'الكابتن للتسويق والخدمات التجارية',
    mainText: 'CAPTAIN',
    subtitleText: 'MARKETING',
    mainFontId: 'archivo-black',
    mainStyle: { text: 'CAPTAIN', fontSize: 62, fontWeight: 950, letterSpacing: 0.1, lineHeight: 1, uppercase: true, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'MARKETING', fontSize: 11, fontWeight: 800, letterSpacing: 0.4, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.9 },
    bgColor: '#09090b', textColor: '#ffffff', accentColor: '#e4e4e7',
    bgConfig: { type: 'solid', colorStart: '#09090b', colorEnd: '#1f2937', angle: 90 },
    borderType: 'accent-line', category: 'display', row: 16
  },
  {
    id: 'preset-bosten',
    presetName: 'Bosten',
    arabicPresetName: 'شعار Bosten الفخم للمجلات والمصورين',
    title: 'Bosten',
    arabicTitle: 'بوسطن لإنتاج المقاطع واستوديو الفن',
    mainText: 'Bosten',
    subtitleText: 'PHOTO STUDIOS',
    mainFontId: 'playfair-display',
    mainStyle: { text: 'Bosten', fontSize: 75, fontWeight: 800, letterSpacing: 0.05, lineHeight: 1.1, uppercase: false, italic: false, textShadow: 'none' },
    subtitleFontId: 'inter',
    subtitleStyle: { text: 'PHOTO STUDIOS', fontSize: 11, fontWeight: 650, letterSpacing: 0.35, uppercase: true, italic: false, fontFamily: '"Inter", sans-serif', visible: true, opacity: 0.85 },
    bgColor: '#171717', textColor: '#ffffff', accentColor: '#cbd5e1',
    bgConfig: { type: 'gradient', colorStart: '#1c1917', colorEnd: '#000000', angle: 180 },
    borderType: 'thin', category: 'serif', row: 16
  }
];

