import { LogoPreset } from './types';

export const IMAGE_PRESETS_CATALOG: LogoPreset[] = [
  // ==========================================
  // IMAGE 1 PRESETS: GOTHIC, MEDIEVAL & CURSIVE SIGNATURES
  // ==========================================
  {
    id: 'img-preset-will',
    title: 'Will',
    arabicTitle: 'شعاع العزيمة - Will',
    presetName: 'Will (Teutonic3)',
    arabicPresetName: 'شعار Will القوطي الفخم',
    mainText: 'Will',
    subtitleText: 'TEUTONIC3 HERITAGE DESIGN',
    mainFontId: 'unifrakturmaguntia',
    mainStyle: {
      text: 'Will',
      fontSize: 100,
      fontWeight: 700,
      letterSpacing: 0.02,
      lineHeight: 1.1,
      uppercase: false,
      italic: false,
      textShadow: 'subtle'
    },
    subtitleFontId: 'space-mono',
    subtitleStyle: {
      text: 'TEUTONIC3 HERITAGE DESIGN',
      fontSize: 10,
      fontWeight: 500,
      letterSpacing: 0.25,
      uppercase: true,
      italic: false,
      fontFamily: '"Space Mono", monospace',
      visible: true,
      opacity: 0.8
    },
    bgColor: '#0d0d0d',
    textColor: '#ffffff',
    accentColor: '#c5a88a',
    bgConfig: { type: 'radial', colorStart: '#1a1a1a', colorEnd: '#000000', angle: 180 },
    borderType: 'accent-line',
    category: 'display',
    row: 1
  },
  {
    id: 'img-preset-sinner',
    title: 'Sinner',
    arabicTitle: 'العاصف - Sinner',
    presetName: 'Sinner (The Sinatra)',
    arabicPresetName: 'شعار Sinner الخط الكلاسيكي',
    mainText: 'Sinner',
    subtitleText: 'THE SINATRA SPECIAL SPECIFICATION',
    mainFontId: 'arizonia',
    mainStyle: {
      text: 'Sinner',
      fontSize: 90,
      fontWeight: 400,
      letterSpacing: 0,
      lineHeight: 1.1,
      uppercase: false,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'cinzel',
    subtitleStyle: {
      text: 'THE SINATRA SPECIAL SPECIFICATION',
      fontSize: 9,
      fontWeight: 700,
      letterSpacing: 0.3,
      uppercase: true,
      italic: false,
      fontFamily: '"Cinzel", serif',
      visible: true,
      opacity: 0.75
    },
    bgColor: '#121212',
    textColor: '#fafaf6',
    accentColor: '#eb5e28',
    bgConfig: { type: 'gradient', colorStart: '#1d1a18', colorEnd: '#0d0b0a', angle: 135 },
    borderType: 'none',
    category: 'script',
    row: 1
  },
  {
    id: 'img-preset-saber',
    title: 'Saber',
    arabicTitle: 'السيف - Saber',
    presetName: 'Saber (Bambi Regular)',
    arabicPresetName: 'شعار Saber بخط اليد الرقيق',
    mainText: 'Saber',
    subtitleText: 'BAMBI REGULAR ORIGINAL PRESETS',
    mainFontId: 'sacramento',
    mainStyle: {
      text: 'Saber',
      fontSize: 105,
      fontWeight: 400,
      letterSpacing: 0.05,
      lineHeight: 1.1,
      uppercase: false,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'plus-jakarta-sans',
    subtitleStyle: {
      text: 'BAMBI REGULAR ORIGINAL PRESETS',
      fontSize: 9,
      fontWeight: 600,
      letterSpacing: 0.35,
      uppercase: true,
      italic: false,
      fontFamily: '"Plus Jakarta Sans", sans-serif',
      visible: true,
      opacity: 0.8
    },
    bgColor: '#0f1011',
    textColor: '#fbf4eb',
    accentColor: '#c5a88a',
    bgConfig: { type: 'solid', colorStart: '#0f1011', colorEnd: '#000000', angle: 180 },
    borderType: 'rounded',
    category: 'script',
    row: 1
  },
  {
    id: 'img-preset-night',
    title: 'Night',
    arabicTitle: 'الليل الحالك - Night',
    presetName: 'Night (Klaber Fraktur)',
    arabicPresetName: 'شعار Night القوطي الثقيل',
    mainText: 'Night',
    subtitleText: 'KLABER FRAKTUR HISTORIC GOLD',
    mainFontId: 'unifrakturcook',
    mainStyle: {
      text: 'Night',
      fontSize: 95,
      fontWeight: 700,
      letterSpacing: 0.03,
      lineHeight: 1.1,
      uppercase: false,
      italic: false,
      textShadow: 'glow'
    },
    subtitleFontId: 'jetbrains-mono',
    subtitleStyle: {
      text: 'KLABER FRAKTUR HISTORIC GOLD',
      fontSize: 9,
      fontWeight: 500,
      letterSpacing: 0.25,
      uppercase: true,
      italic: false,
      fontFamily: '"JetBrains Mono", monospace',
      visible: true,
      opacity: 0.85
    },
    bgColor: '#090a0c',
    textColor: '#ffffff',
    accentColor: '#f59e0b',
    bgConfig: { type: 'radial', colorStart: '#1e2026', colorEnd: '#060708', angle: 180 },
    borderType: 'accent-line',
    category: 'display',
    row: 1
  },
  {
    id: 'img-preset-joke',
    title: 'Joke',
    arabicTitle: 'المهزلة - Joke',
    presetName: 'Joke (The Bjoke)',
    arabicPresetName: 'شعار Joke ذو الأطراف الحادة',
    mainText: 'Joke',
    subtitleText: 'THE BJOKE ARCHITECTURE DUALITY',
    mainFontId: 'metal-mania',
    mainStyle: {
      text: 'Joke',
      fontSize: 88,
      fontWeight: 400,
      letterSpacing: 0.06,
      lineHeight: 1.1,
      uppercase: false,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'space-grotesk',
    subtitleStyle: {
      text: 'THE BJOKE ARCHITECTURE DUALITY',
      fontSize: 10,
      fontWeight: 700,
      letterSpacing: 0.2,
      uppercase: true,
      italic: false,
      fontFamily: '"Space Grotesk", sans-serif',
      visible: true,
      opacity: 0.8
    },
    bgColor: '#17181c',
    textColor: '#eef2f6',
    accentColor: '#94a3b8',
    bgConfig: { type: 'solid', colorStart: '#17181c', colorEnd: '#000000', angle: 180 },
    borderType: 'thin',
    category: 'display',
    row: 1
  },
  {
    id: 'img-preset-ending',
    title: 'Ending',
    arabicTitle: 'الخاتمة - Ending',
    presetName: 'Ending (Masha)',
    arabicPresetName: 'شعار Ending بالريشة الفنية الكثيفة',
    mainText: 'Ending',
    subtitleText: 'MASHA TEXTILE ART APPAREL',
    mainFontId: 'kaushan-script',
    mainStyle: {
      text: 'Ending',
      fontSize: 82,
      fontWeight: 400,
      letterSpacing: 0,
      lineHeight: 1.2,
      uppercase: false,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'inter',
    subtitleStyle: {
      text: 'MASHA TEXTILE ART APPAREL',
      fontSize: 10,
      fontWeight: 600,
      letterSpacing: 0.3,
      uppercase: true,
      italic: false,
      fontFamily: '"Inter", sans-serif',
      visible: true,
      opacity: 0.75
    },
    bgColor: '#141215',
    textColor: '#faecff',
    accentColor: '#d946ef',
    bgConfig: { type: 'gradient', colorStart: '#201625', colorEnd: '#09050d', angle: 180 },
    borderType: 'none',
    category: 'script',
    row: 1
  },
  {
    id: 'img-preset-hide',
    title: 'Hide',
    arabicTitle: 'الحجاب - Hide',
    presetName: 'Hide (Z-Murrano)',
    arabicPresetName: 'شعار Hide بتوقيع الخيط الفريد',
    mainText: 'Hide',
    subtitleText: 'Z-MURRANO CUSTOM SIGNATURE LINE',
    mainFontId: 'windsong',
    mainStyle: {
      text: 'Hide',
      fontSize: 110,
      fontWeight: 400,
      letterSpacing: 0.05,
      lineHeight: 1.1,
      uppercase: false,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'cormorant-garamond',
    subtitleStyle: {
      text: 'Z-MURRANO CUSTOM SIGNATURE LINE',
      fontSize: 11,
      fontWeight: 500,
      letterSpacing: 0.3,
      uppercase: true,
      italic: true,
      fontFamily: '"Cormorant Garamond", serif',
      visible: true,
      opacity: 0.8
    },
    bgColor: '#131518',
    textColor: '#f1f5f9',
    accentColor: '#a8a29e',
    bgConfig: { type: 'radial', colorStart: '#1e242a', colorEnd: '#0c0e11', angle: 180 },
    borderType: 'none',
    category: 'script',
    row: 1
  },
  {
    id: 'img-preset-cinco',
    title: 'Cinco',
    arabicTitle: 'الخمسة - Cinco',
    presetName: 'Cinco (Old English Five)',
    arabicPresetName: 'شعار Cinco القوطي الكلاسيكي القديم',
    mainText: 'Cinco',
    subtitleText: 'OLD ENGLISH FIVE CAPSULE EXCLUSIVE',
    mainFontId: 'pirata-one',
    mainStyle: {
      text: 'Cinco',
      fontSize: 88,
      fontWeight: 400,
      letterSpacing: 0.06,
      lineHeight: 1.1,
      uppercase: false,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'space-mono',
    subtitleStyle: {
      text: 'OLD ENGLISH FIVE CAPSULE EXCLUSIVE',
      fontSize: 9,
      fontWeight: 700,
      letterSpacing: 0.28,
      uppercase: true,
      italic: false,
      fontFamily: '"Space Mono", monospace',
      visible: true,
      opacity: 0.75
    },
    bgColor: '#0c0d10',
    textColor: '#ecebf4',
    accentColor: '#818cf8',
    bgConfig: { type: 'gradient', colorStart: '#14161f', colorEnd: '#050608', angle: 135 },
    borderType: 'thick',
    category: 'display',
    row: 1
  },
  {
    id: 'img-preset-last',
    title: 'Last',
    arabicTitle: 'النهاية - Last',
    presetName: 'Last (Lordish)',
    arabicPresetName: 'شعار Last الفاخر بالنمط الأسود',
    mainText: 'Last',
    subtitleText: 'LORDISH ROYAL SELECTION APPAREL',
    mainFontId: 'unifrakturcook',
    mainStyle: {
      text: 'Last',
      fontSize: 95,
      fontWeight: 700,
      letterSpacing: 0.05,
      lineHeight: 1.1,
      uppercase: false,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'cinzel',
    subtitleStyle: {
      text: 'LORDISH ROYAL SELECTION APPAREL',
      fontSize: 10,
      fontWeight: 800,
      letterSpacing: 0.35,
      uppercase: true,
      italic: false,
      fontFamily: '"Cinzel", serif',
      visible: true,
      opacity: 0.85
    },
    bgColor: '#0a0a0b',
    textColor: '#fafaf9',
    accentColor: '#fbbf24',
    bgConfig: { type: 'radial', colorStart: '#202023', colorEnd: '#050506', angle: 180 },
    borderType: 'double',
    category: 'display',
    row: 2
  },
  {
    id: 'img-preset-vintage',
    title: 'VINTAGE',
    arabicTitle: 'العريق - Vintage',
    presetName: 'Vintage (Deluce)',
    arabicPresetName: 'شعار Vintage الكاوتشر الصحفي الراقي',
    mainText: 'VINTAGE',
    subtitleText: 'DELUCE COLLECTION PRESTIGE LONDON',
    mainFontId: 'cinzel-decorative',
    mainStyle: {
      text: 'VINTAGE',
      fontSize: 72,
      fontWeight: 700,
      letterSpacing: 0.15,
      lineHeight: 1.1,
      uppercase: true,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'prata',
    subtitleStyle: {
      text: 'DELUCE COLLECTION PRESTIGE LONDON',
      fontSize: 10,
      fontWeight: 400,
      letterSpacing: 0.4,
      uppercase: true,
      italic: true,
      fontFamily: '"Prata", serif',
      visible: true,
      opacity: 0.8
    },
    bgColor: '#171514',
    textColor: '#fcfcfc',
    accentColor: '#d6d3d1',
    bgConfig: { type: 'solid', colorStart: '#171514', colorEnd: '#0c0a09', angle: 180 },
    borderType: 'accent-line',
    category: 'serif',
    row: 2
  },
  {
    id: 'img-preset-shimmer',
    title: 'Shimmer',
    arabicTitle: 'اللمعان - Shimmer',
    presetName: 'Shimmer (Poppy Shower)',
    arabicPresetName: 'شعار Shimmer الراقص الناعم',
    mainText: 'Shimmer',
    subtitleText: 'POPPY SHOWER BEAUTY SYSTEM',
    mainFontId: 'birthstone-bounce',
    mainStyle: {
      text: 'Shimmer',
      fontSize: 98,
      fontWeight: 400,
      letterSpacing: 0.02,
      lineHeight: 1.1,
      uppercase: false,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'inter',
    subtitleStyle: {
      text: 'POPPY SHOWER BEAUTY SYSTEM',
      fontSize: 10,
      fontWeight: 700,
      letterSpacing: 0.32,
      uppercase: true,
      italic: false,
      fontFamily: '"Inter", sans-serif',
      visible: true,
      opacity: 0.75
    },
    bgColor: '#161115',
    textColor: '#fff1f2',
    accentColor: '#f43f5e',
    bgConfig: { type: 'gradient', colorStart: '#251622', colorEnd: '#090508', angle: 185 },
    borderType: 'none',
    category: 'script',
    row: 2
  },
  {
    id: 'img-preset-flower',
    title: 'Flower',
    arabicTitle: 'الزهرة - Flower',
    presetName: 'Flower (King of Thieves)',
    arabicPresetName: 'شعار Flower اللطيف الكثيف',
    mainText: 'Flower',
    subtitleText: 'KING OF THIEVES SIGN BLOSSOM',
    mainFontId: 'yellowtail',
    mainStyle: {
      text: 'Flower',
      fontSize: 85,
      fontWeight: 400,
      letterSpacing: 0,
      lineHeight: 1.2,
      uppercase: false,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'plus-jakarta-sans',
    subtitleStyle: {
      text: 'KING OF THIEVES SIGN BLOSSOM',
      fontSize: 10,
      fontWeight: 600,
      letterSpacing: 0.25,
      uppercase: true,
      italic: false,
      fontFamily: '"Plus Jakarta Sans", sans-serif',
      visible: true,
      opacity: 0.8
    },
    bgColor: '#101715',
    textColor: '#f0fdf4',
    accentColor: '#4ade80',
    bgConfig: { type: 'radial', colorStart: '#142921', colorEnd: '#070a09', angle: 180 },
    borderType: 'rounded',
    category: 'script',
    row: 2
  },
  {
    id: 'img-preset-low',
    title: 'Low',
    arabicTitle: 'المنخفض - Low',
    presetName: 'Low (Osgard Pro)',
    arabicPresetName: 'شعار Low العتيق بالانحناء المتقاطع',
    mainText: 'Low',
    subtitleText: 'OSGARD PRO MEDIEVAL RETROSPECTIVE',
    mainFontId: 'unifrakturmaguntia',
    mainStyle: {
      text: 'Low',
      fontSize: 92,
      fontWeight: 700,
      letterSpacing: 0.04,
      lineHeight: 1.1,
      uppercase: false,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'space-mono',
    subtitleStyle: {
      text: 'OSGARD PRO MEDIEVAL RETROSPECTIVE',
      fontSize: 9,
      fontWeight: 600,
      letterSpacing: 0.3,
      uppercase: true,
      italic: false,
      fontFamily: '"Space Mono", monospace',
      visible: true,
      opacity: 0.8
    },
    bgColor: '#0a0a0a',
    textColor: '#fafaf9',
    accentColor: '#e5e5e5',
    bgConfig: { type: 'solid', colorStart: '#0a0a0a', colorEnd: '#1a1a1a', angle: 180 },
    borderType: 'accent-line',
    category: 'display',
    row: 2
  },
  {
    id: 'img-preset-stars',
    title: 'Stars',
    arabicTitle: 'النجوم - Stars',
    presetName: 'Stars (Keyline Regular)',
    arabicPresetName: 'شعار Stars بخط الفرشاة المستدير مظهر الكرتون',
    mainText: 'Stars',
    subtitleText: 'KEYLINE REGULAR ESTABLISHED EMBLEM',
    mainFontId: 'lobster',
    mainStyle: {
      text: 'Stars',
      fontSize: 88,
      fontWeight: 400,
      letterSpacing: 0.02,
      lineHeight: 1.1,
      uppercase: false,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'inter',
    subtitleStyle: {
      text: 'KEYLINE REGULAR ESTABLISHED EMBLEM',
      fontSize: 10,
      fontWeight: 700,
      letterSpacing: 0.28,
      uppercase: true,
      italic: false,
      fontFamily: '"Inter", sans-serif',
      visible: true,
      opacity: 0.85
    },
    bgColor: '#171212',
    textColor: '#fff5f5',
    accentColor: '#f87171',
    bgConfig: { type: 'gradient', colorStart: '#2a1a1a', colorEnd: '#0d0707', angle: 135 },
    borderType: 'none',
    category: 'script',
    row: 2
  },
  {
    id: 'img-preset-ruin',
    title: 'Ruin',
    arabicTitle: 'الخراب - Ruin',
    presetName: 'Ruin (Shella Clean)',
    arabicPresetName: 'شعار Ruin الفني الحديث بخط ريفي ناعم',
    mainText: 'Ruin',
    subtitleText: 'SHELLA CLEAN DESIGN INNOVATION LAB',
    mainFontId: 'caveat',
    mainStyle: {
      text: 'Ruin',
      fontSize: 98,
      fontWeight: 700,
      letterSpacing: 0,
      lineHeight: 1.1,
      uppercase: false,
      italic: true,
      textShadow: 'none'
    },
    subtitleFontId: 'space-grotesk',
    subtitleStyle: {
      text: 'SHELLA CLEAN DESIGN INNOVATION LAB',
      fontSize: 10,
      fontWeight: 500,
      letterSpacing: 0.25,
      uppercase: true,
      italic: false,
      fontFamily: '"Space Grotesk", sans-serif',
      visible: true,
      opacity: 0.8
    },
    bgColor: '#111316',
    textColor: '#f1f5f9',
    accentColor: '#38bdf8',
    bgConfig: { type: 'solid', colorStart: '#111316', colorEnd: '#000000', angle: 180 },
    borderType: 'rounded',
    category: 'script',
    row: 2
  },
  {
    id: 'img-preset-yearn',
    title: 'Yearn',
    arabicTitle: 'الشوق - Yearn',
    presetName: 'Yearn (Lucinda Script)',
    arabicPresetName: 'شعار Yearn ذو الحلقات الملكية الطويلة',
    mainText: 'Yearn',
    subtitleText: 'LUCINDA SCRIPT ESTHETIQUE PARIS',
    mainFontId: 'tangerine',
    mainStyle: {
      text: 'Yearn',
      fontSize: 125,
      fontWeight: 700,
      letterSpacing: 0.05,
      lineHeight: 1.1,
      uppercase: false,
      italic: true,
      textShadow: 'none'
    },
    subtitleFontId: 'cinzel',
    subtitleStyle: {
      text: 'LUCINDA SCRIPT ESTHETIQUE PARIS',
      fontSize: 12,
      fontWeight: 800,
      letterSpacing: 0.35,
      uppercase: true,
      italic: false,
      fontFamily: '"Cinzel", serif',
      visible: true,
      opacity: 0.9
    },
    bgColor: '#141416',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    bgConfig: { type: 'radial', colorStart: '#202025', colorEnd: '#09090b', angle: 180 },
    borderType: 'none',
    category: 'script',
    row: 2
  },

  // ==========================================
  // IMAGE 2 PRESETS: FUTURISTIC, SAN-SERIF GEOMETRIC & EDITORIAL
  // ==========================================
  {
    id: 'img-preset-sonreir',
    title: 'SONREÍR',
    arabicTitle: 'الابتسامة - SONREÍR',
    presetName: 'Sonreír (Medusa Gothic)',
    arabicPresetName: 'شعار SONREÍR البسيط ذو المسافة الواسعة',
    mainText: 'SONREÍR',
    subtitleText: 'MEDUSA GOTHIC PREMIUM MINIMAL DESIGN',
    mainFontId: 'cormorant-garamond',
    mainStyle: {
      text: 'SONREÍR',
      fontSize: 70,
      fontWeight: 500,
      letterSpacing: 0.08,
      lineHeight: 1.1,
      uppercase: true,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'inter',
    subtitleStyle: {
      text: 'MEDUSA GOTHIC PREMIUM MINIMAL DESIGN',
      fontSize: 10,
      fontWeight: 700,
      letterSpacing: 0.35,
      uppercase: true,
      italic: false,
      fontFamily: '"Inter", sans-serif',
      visible: true,
      opacity: 0.8
    },
    bgColor: '#0f1115',
    textColor: '#ecebf4',
    accentColor: '#38bdf8',
    bgConfig: { type: 'radial', colorStart: '#1d222d', colorEnd: '#08090c', angle: 180 },
    borderType: 'none',
    category: 'serif',
    row: 3
  },
  {
    id: 'img-preset-break',
    title: 'BREAK',
    arabicTitle: 'الكسر - BREAK',
    presetName: 'Break (Brightness)',
    arabicPresetName: 'شعار BREAK ذو التقطيع والزوايا الحادة',
    mainText: 'BREAK',
    subtitleText: 'BRIGHTNESS STUDIO TECH SPECIFICATIONS',
    mainFontId: 'syncopate',
    mainStyle: {
      text: 'BREAK',
      fontSize: 65,
      fontWeight: 750,
      letterSpacing: 0.12,
      lineHeight: 1,
      uppercase: true,
      italic: false,
      textShadow: 'glow'
    },
    subtitleFontId: 'space-mono',
    subtitleStyle: {
      text: 'BRIGHTNESS STUDIO TECH SPECIFICATIONS',
      fontSize: 9,
      fontWeight: 700,
      letterSpacing: 0.4,
      uppercase: true,
      italic: true,
      fontFamily: '"Space Mono", monospace',
      visible: true,
      opacity: 0.85
    },
    bgColor: '#0b0c10',
    textColor: '#ffffff',
    accentColor: '#00f2fe',
    bgConfig: { type: 'gradient', colorStart: '#111424', colorEnd: '#030408', angle: 135 },
    borderType: 'accent-line',
    category: 'display',
    row: 3
  },
  {
    id: 'img-preset-won',
    title: 'WON',
    arabicTitle: 'الفوز - WON',
    presetName: 'Won (Quinn)',
    arabicPresetName: 'شعار WON ذو الأعواد المتقاطعة العالية',
    mainText: 'WON',
    subtitleText: 'QUINN DE COUTURE LUXURY PARIS BRAND',
    mainFontId: 'antonio',
    mainStyle: {
      text: 'WON',
      fontSize: 92,
      fontWeight: 700,
      letterSpacing: 0.05,
      lineHeight: 1,
      uppercase: true,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'inter',
    subtitleStyle: {
      text: 'QUINN DE COUTURE LUXURY PARIS BRAND',
      fontSize: 10,
      fontWeight: 700,
      letterSpacing: 0.45,
      uppercase: true,
      italic: false,
      fontFamily: '"Inter", sans-serif',
      visible: true,
      opacity: 0.8
    },
    bgColor: '#0a0a0a',
    textColor: '#ffffff',
    accentColor: '#dfc28d',
    bgConfig: { type: 'solid', colorStart: '#0a0a0a', colorEnd: '#1e1c18', angle: 180 },
    borderType: 'none',
    category: 'sans',
    row: 3
  },
  {
    id: 'img-preset-exo',
    title: 'EXO',
    arabicTitle: 'إكسو الخارجي - EXO',
    presetName: 'Exo (Exodus Demo)',
    arabicPresetName: 'شعار EXO التجريبي الخيال العلمي',
    mainText: 'EXO',
    subtitleText: 'EXODUS DEMO EXPERIMENT PROTOCOLS',
    mainFontId: 'space-grotesk',
    mainStyle: {
      text: 'EXO',
      fontSize: 82,
      fontWeight: 800,
      letterSpacing: 0.1,
      lineHeight: 1,
      uppercase: true,
      italic: false,
      textShadow: 'glow'
    },
    subtitleFontId: 'jetbrains-mono',
    subtitleStyle: {
      text: 'EXODUS DEMO EXPERIMENT PROTOCOLS',
      fontSize: 10,
      fontWeight: 400,
      letterSpacing: 0.28,
      uppercase: true,
      italic: false,
      fontFamily: '"JetBrains Mono", monospace',
      visible: true,
      opacity: 0.8
    },
    bgColor: '#121214',
    textColor: '#ffffff',
    accentColor: '#3b82f6',
    bgConfig: { type: 'radial', colorStart: '#1d1e26', colorEnd: '#09090b', angle: 180 },
    borderType: 'rounded',
    category: 'sans',
    row: 3
  },
  {
    id: 'img-preset-stone',
    title: 'STONE',
    arabicTitle: 'الصخر - STONE',
    presetName: 'Stone (Guardians)',
    arabicPresetName: 'شعار STONE الجريء للألعاب والمستقبل',
    mainText: 'STONE',
    subtitleText: 'GUARDIANS INTELLECTUAL ENTERPRISES',
    mainFontId: 'unbounded',
    mainStyle: {
      text: 'STONE',
      fontSize: 68,
      fontWeight: 900,
      letterSpacing: 0.08,
      lineHeight: 1,
      uppercase: true,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'space-mono',
    subtitleStyle: {
      text: 'GUARDIANS INTELLECTUAL ENTERPRISES',
      fontSize: 10,
      fontWeight: 600,
      letterSpacing: 0.35,
      uppercase: true,
      italic: true,
      fontFamily: '"Space Mono", monospace',
      visible: true,
      opacity: 0.85
    },
    bgColor: '#17171a',
    textColor: '#ffffff',
    accentColor: '#fb923c',
    bgConfig: { type: 'solid', colorStart: '#17171a', colorEnd: '#09090b', angle: 180 },
    borderType: 'accent-line',
    category: 'sans',
    row: 3
  },
  {
    id: 'img-preset-under',
    title: 'UNDER',
    arabicTitle: 'العمق السفلي - UNDER',
    presetName: 'Under (Devil Breeze Book)',
    arabicPresetName: 'شعار UNDER الدائري البسيط والرحب',
    mainText: 'UNDER',
    subtitleText: 'DEVIL BREEZE BOOK PUBLISHING GROUP',
    mainFontId: 'comfortaa',
    mainStyle: {
      text: 'UNDER',
      fontSize: 75,
      fontWeight: 500,
      letterSpacing: 0.15,
      lineHeight: 1.1,
      uppercase: true,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'space-grotesk',
    subtitleStyle: {
      text: 'DEVIL BREEZE BOOK PUBLISHING GROUP',
      fontSize: 10,
      fontWeight: 700,
      letterSpacing: 0.28,
      uppercase: true,
      italic: false,
      fontFamily: '"Space Grotesk", sans-serif',
      visible: true,
      opacity: 0.8
    },
    bgColor: '#151619',
    textColor: '#fafbfe',
    accentColor: '#f1f5f9',
    bgConfig: { type: 'radial', colorStart: '#20222a', colorEnd: '#0d0e11', angle: 180 },
    borderType: 'none',
    category: 'sans',
    row: 3
  },
  {
    id: 'img-preset-volar',
    title: 'VOLAR',
    arabicTitle: 'الطيران - VOLAR',
    presetName: 'Volar (Blacklisted)',
    arabicPresetName: 'شعار VOLAR العريض الممتد الصناعي',
    mainText: 'VOLAR',
    subtitleText: 'BLACKLISTED STREETWEAR METROPOLIS EX',
    mainFontId: 'anton',
    mainStyle: {
      text: 'VOLAR',
      fontSize: 82,
      fontWeight: 900,
      letterSpacing: 0.05,
      lineHeight: 1,
      uppercase: true,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'space-mono',
    subtitleStyle: {
      text: 'BLACKLISTED STREETWEAR METROPOLIS EX',
      fontSize: 10,
      fontWeight: 700,
      letterSpacing: 0.32,
      uppercase: true,
      italic: true,
      fontFamily: '"Space Mono", monospace',
      visible: true,
      opacity: 0.75
    },
    bgColor: '#0f0f11',
    textColor: '#ffffff',
    accentColor: '#9ca3af',
    bgConfig: { type: 'gradient', colorStart: '#17171c', colorEnd: '#09090b', angle: 180 },
    borderType: 'thin',
    category: 'display',
    row: 3
  },
  {
    id: 'img-preset-sunny',
    title: 'SUNNY',
    arabicTitle: 'المشرق - SUNNY',
    presetName: 'Sunny (Floresh)',
    arabicPresetName: 'شعار SUNNY المائل السريع الحاد',
    mainText: 'SUNNY',
    subtitleText: 'FLORESH SPEED INNOVATIVE LABS',
    mainFontId: 'orbitron',
    mainStyle: {
      text: 'SUNNY',
      fontSize: 72,
      fontWeight: 900,
      letterSpacing: 0.1,
      lineHeight: 1.1,
      uppercase: true,
      italic: true,
      textShadow: 'glow'
    },
    subtitleFontId: 'space-grotesk',
    subtitleStyle: {
      text: 'FLORESH SPEED INNOVATIVE LABS',
      fontSize: 9,
      fontWeight: 700,
      letterSpacing: 0.35,
      uppercase: true,
      italic: false,
      fontFamily: '"Space Grotesk", sans-serif',
      visible: true,
      opacity: 0.85
    },
    bgColor: '#0a0a0c',
    textColor: '#ffffff',
    accentColor: '#22c55e',
    bgConfig: { type: 'gradient', colorStart: '#14141d', colorEnd: '#060608', angle: 145 },
    borderType: 'none',
    category: 'sans',
    row: 3
  },
  {
    id: 'img-preset-march',
    title: 'MARCH',
    arabicTitle: 'مارس آذار - MARCH',
    presetName: 'March (Bohem Press)',
    arabicPresetName: 'شعار MARCH الكلاسيكي المطبعي العريق',
    mainText: 'MARCH',
    subtitleText: 'BOHEM PRESS BRAND WOODBLOCK ED',
    mainFontId: 'rye',
    mainStyle: {
      text: 'MARCH',
      fontSize: 62,
      fontWeight: 400,
      letterSpacing: 0.08,
      lineHeight: 1.1,
      uppercase: true,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'space-mono',
    subtitleStyle: {
      text: 'BOHEM PRESS BRAND WOODBLOCK ED',
      fontSize: 10,
      fontWeight: 700,
      letterSpacing: 0.3,
      uppercase: true,
      italic: false,
      fontFamily: '"Space Mono", monospace',
      visible: true,
      opacity: 0.8
    },
    bgColor: '#1c1714',
    textColor: '#faf6f0',
    accentColor: '#ea580c',
    bgConfig: { type: 'solid', colorStart: '#1c1714', colorEnd: '#000000', angle: 180 },
    borderType: 'thick',
    category: 'display',
    row: 4
  },
  {
    id: 'img-preset-fire',
    title: 'FIRE',
    arabicTitle: 'النار - FIRE',
    presetName: 'Fire (Azonix-1vb0)',
    arabicPresetName: 'شعار FIRE المستقبلي الفضائي',
    mainText: 'FIRE',
    subtitleText: 'AZONIX-1VB0 MILITARY VEHICLES SEC',
    mainFontId: 'syncopate',
    mainStyle: {
      text: 'FIRE',
      fontSize: 68,
      fontWeight: 700,
      letterSpacing: 0.16,
      lineHeight: 1,
      uppercase: true,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'jetbrains-mono',
    subtitleStyle: {
      text: 'AZONIX-1VB0 MILITARY VEHICLES SEC',
      fontSize: 9,
      fontWeight: 650,
      letterSpacing: 0.32,
      uppercase: true,
      italic: false,
      fontFamily: '"JetBrains Mono", monospace',
      visible: true,
      opacity: 0.8
    },
    bgColor: '#09090b',
    textColor: '#ffffff',
    accentColor: '#ef4444',
    bgConfig: { type: 'gradient', colorStart: '#1c1010', colorEnd: '#050506', angle: 180 },
    borderType: 'accent-line',
    category: 'display',
    row: 4
  },
  {
    id: 'img-preset-occur',
    title: 'Occur',
    arabicTitle: 'الحدوث - Occur',
    presetName: 'Occur (Wallington Regular)',
    arabicPresetName: 'شعار Occur فيكتوري ذو خطوط متموجة للكتب',
    mainText: 'Occur',
    subtitleText: 'WALLINGTON REGULAR INCORPORATED',
    mainFontId: 'cinzel-decorative',
    mainStyle: {
      text: 'Occur',
      fontSize: 75,
      fontWeight: 700,
      letterSpacing: 0.05,
      lineHeight: 1.1,
      uppercase: false,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'playfair-display',
    subtitleStyle: {
      text: 'WALLINGTON REGULAR INCORPORATED',
      fontSize: 10,
      fontWeight: 600,
      letterSpacing: 0.3,
      uppercase: true,
      italic: true,
      fontFamily: '"Playfair Display", serif',
      visible: true,
      opacity: 0.8
    },
    bgColor: '#17141d',
    textColor: '#faf6ff',
    accentColor: '#c084fc',
    bgConfig: { type: 'radial', colorStart: '#251e33', colorEnd: '#09070d', angle: 180 },
    borderType: 'none',
    category: 'serif',
    row: 4
  },
  {
    id: 'img-preset-run',
    title: 'RUN',
    arabicTitle: 'الركض - RUN',
    presetName: 'Run (Panthera Regular)',
    arabicPresetName: 'شعار RUN ذو الخطوط الإبزيمية للرياضيين',
    mainText: 'RUN',
    subtitleText: 'PANTHERA REGULAR ACTIVE SPORTSWEAR',
    mainFontId: 'graduate',
    mainStyle: {
      text: 'RUN',
      fontSize: 78,
      fontWeight: 400,
      letterSpacing: 0.08,
      lineHeight: 1,
      uppercase: true,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'inter',
    subtitleStyle: {
      text: 'PANTHERA REGULAR ACTIVE SPORTSWEAR',
      fontSize: 10,
      fontWeight: 700,
      letterSpacing: 0.35,
      uppercase: true,
      italic: false,
      fontFamily: '"Inter", sans-serif',
      visible: true,
      opacity: 0.85
    },
    bgColor: '#100a12',
    textColor: '#ffffff',
    accentColor: '#d946ef',
    bgConfig: { type: 'gradient', colorStart: '#201124', colorEnd: '#080409', angle: 135 },
    borderType: 'double',
    category: 'display',
    row: 4
  },
  {
    id: 'img-preset-venom',
    title: 'Venom',
    arabicTitle: 'السم - Venom',
    presetName: 'Venom (Better Signature)',
    arabicPresetName: 'شعار Venom ذو التوقيع السائل المنخفض والممتد',
    mainText: 'Venom',
    subtitleText: 'BETTER SIGNATURE STYLISH COUTURE',
    mainFontId: 'windsong',
    mainStyle: {
      text: 'Venom',
      fontSize: 105,
      fontWeight: 400,
      letterSpacing: 0.01,
      lineHeight: 1.1,
      uppercase: false,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'plus-jakarta-sans',
    subtitleStyle: {
      text: 'BETTER SIGNATURE STYLISH COUTURE',
      fontSize: 9,
      fontWeight: 600,
      letterSpacing: 0.4,
      uppercase: true,
      italic: false,
      fontFamily: '"Plus Jakarta Sans", sans-serif',
      visible: true,
      opacity: 0.8
    },
    bgColor: '#141416',
    textColor: '#fefefe',
    accentColor: '#f43f5e',
    bgConfig: { type: 'solid', colorStart: '#141416', colorEnd: '#050506', angle: 180 },
    borderType: 'none',
    category: 'script',
    row: 4
  },
  {
    id: 'img-preset-toxic',
    title: 'TOXIC',
    arabicTitle: 'السام - TOXIC',
    presetName: 'Toxic (Beauty of the Beast)',
    arabicPresetName: 'شعار TOXIC الرومانسي الممتد لعلامات التجميل',
    mainText: 'TOXIC',
    subtitleText: 'BEAUTY OF THE BEAST SHIELD OF PARADISE',
    mainFontId: 'prata',
    mainStyle: {
      text: 'TOXIC',
      fontSize: 75,
      fontWeight: 400,
      letterSpacing: 0.1,
      lineHeight: 1.1,
      uppercase: true,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'cormorant-garamond',
    subtitleStyle: {
      text: 'BEAUTY OF THE BEAST SHIELD OF PARADISE',
      fontSize: 11,
      fontWeight: 600,
      letterSpacing: 0.3,
      uppercase: true,
      italic: true,
      fontFamily: '"Cormorant Garamond", serif',
      visible: true,
      opacity: 0.8
    },
    bgColor: '#171215',
    textColor: '#fff1f2',
    accentColor: '#fda4af',
    bgConfig: { type: 'gradient', colorStart: '#271b22', colorEnd: '#0e0b0d', angle: 155 },
    borderType: 'none',
    category: 'serif',
    row: 4
  },
  {
    id: 'img-preset-dust',
    title: 'DUST',
    arabicTitle: 'الغبار - DUST',
    presetName: 'Dust (Toreadore NY64)',
    arabicPresetName: 'شعار DUST المطبعي المتآكل الشجاع',
    mainText: 'DUST',
    subtitleText: 'TOREADORE NY64 INDUSTRIAL CARGO SECTORS',
    mainFontId: 'special-elite',
    mainStyle: {
      text: 'DUST',
      fontSize: 76,
      fontWeight: 400,
      letterSpacing: 0.08,
      lineHeight: 1.1,
      uppercase: true,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'space-mono',
    subtitleStyle: {
      text: 'TOREPLAY DUST INDUSTRIAL LOGISTIC SECTOR',
      fontSize: 10,
      fontWeight: 600,
      letterSpacing: 0.28,
      uppercase: true,
      italic: false,
      fontFamily: '"Space Mono", monospace',
      visible: true,
      opacity: 0.8
    },
    bgColor: '#141416',
    textColor: '#eae9e9',
    accentColor: '#fbbf24',
    bgConfig: { type: 'grid', colorStart: '#141416', colorEnd: '#000000', angle: 180, gridColor: 'rgba(251,191,36,0.05)' },
    borderType: 'accent-line',
    category: 'display',
    row: 4
  },
  {
    id: 'img-preset-ideal',
    title: 'Ideal',
    arabicTitle: 'المثالي - Ideal',
    presetName: 'Ideal (Afrah Bold)',
    arabicPresetName: 'شعار Ideal التحريري الفاخر المجلات',
    mainText: 'Ideal',
    subtitleText: 'AFRAH BOLD ESTABLISHED GENTLEMANS CL',
    mainFontId: 'dm-serif-display',
    mainStyle: {
      text: 'Ideal',
      fontSize: 78,
      fontWeight: 400,
      letterSpacing: 0.02,
      lineHeight: 1.1,
      uppercase: false,
      italic: false,
      textShadow: 'none'
    },
    subtitleFontId: 'plus-jakarta-sans',
    subtitleStyle: {
      text: 'AFRAH BOLD ESTABLISHED GENTLEMANS CLUB',
      fontSize: 10,
      fontWeight: 700,
      letterSpacing: 0.32,
      uppercase: true,
      italic: false,
      fontFamily: '"Plus Jakarta Sans", sans-serif',
      visible: true,
      opacity: 0.85
    },
    bgColor: '#161311',
    textColor: '#f5efe6',
    accentColor: '#c5a88a',
    bgConfig: { type: 'radial', colorStart: '#2a221d', colorEnd: '#0c0a09', angle: 180 },
    borderType: 'none',
    category: 'serif',
    row: 4
  }
];
